 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('associadosNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listaAssociados'); ?>">Associados</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar associado</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="progress" id="progresso" style="display: none">
                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                      Carregando...
                    </div>
                  </div>
                  <?php echo $this->partial('form/associado', array('form'=> $formAssociado, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <!-- FORM, vincular arquivos -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Vincular arquivos ao associado</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formArquivo, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>

    <!-- Listar arquivos -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <h3 class="panel-title">Arquivos vinculados ao associado</h3>
            </div>
            <div class="panel-body">
              <?php if($arquivos->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Descrição</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($arquivos as $arquivo): ?>
              <tr>
                <td style="text-align: center"><?= $arquivo['descricao']; ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/download.png'); ?>" title="Download" 
                  onclick="location.href='<?= $this->url('downloadArquivoIndividual', array('idArquivo' => $arquivo['id'])); ?>'" style="cursor: pointer;">
                  <span style="margin-right:4px;"></span>  
                  <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Excluir" 
                  onclick="alerta('<?= $this->url('deletarArquivoIndividualAssociado', array('idAssociado' => $idAssociado, 'idArquivo' => $arquivo['id'])); ?>', 'deletar');" style="cursor: pointer;">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhum arquivo vinculado ao associado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

    <script type="text/javascript">
      $(document).ready(function() {
        formInscricao();
        carregarPais(<?= $associado['pais_endereco'] ?>);
      });
    </script>