<div class="container theme-showcase" role="main" style="">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                  <form class="form-inline" role="form" method="POST" action="#">
                      <div class="row">
                        <?php if(!$empresa): ?>
                          <div class='col-sm-4'>
                            <div class="form-group">
                              <label for="disabledTextInput"><?= $formPesquisa->get('empresa')->getLabel(); ?></label>
                              <?= $this->formElement($formPesquisa->get('empresa')); ?>
                            </div>
                          </div>
                        <?php endif; ?>
                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('nome_completo')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('nome_completo')); ?>
                          </div>
                        </div>

                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('cpf')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('cpf')); ?>
                          </div>
                        </div>

                        

                      </div>

                      <div class="row" style="margin-top:20px;">
                        <button type="submit" name="pesquisar" class="btn btn-success" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                        <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                      </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('associadosNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

      <button type="button" class="btn btn-danger" onclick="location.href='<?= $this->url('importarAssociados'); ?>'" style="float: right;margin-right: 5px; width:100px;">
      <img src="<?php echo $this->basePath('img/excel.png') ?>" alt="Novo">
      Importar</button>

      <button type="button" class="btn btn-primary" onclick="location.href='<?= $this->url('exportarAssociados'); ?>'" style="float: right;margin-right: 5px; width:100px;">
      <img src="<?php echo $this->basePath('img/excel.png') ?>" alt="Novo">
      Exportar</button>

      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Associados</li>
      </ol>
    </div>



    <!-- LISTAGEM DOS EQUIPAMENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de associados</h3>
            </div>
            <div class="panel-body">
              <?php if($associados->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Empresa</th>
                  <th style="text-align: center">Nome</th>
                  <th style="text-align: center">CPF</th>
                  <th style="text-align: center">Categoria do associado</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($associados as $associado): ?>
              <tr>
                <td style="text-align: center"><?= $associado['nome_fantasia']; ?></td>
                <td style="text-align: center"><?= $associado['nome_completo']; ?></td>
                <td style="text-align: center"><?= $associado['cpf']; ?></td>
                <td style="text-align: center"><?= $associado['nome_categoria']; ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                  onclick="location.href='<?= $this->url('associadosAlterar', array('id' => $associado['id'])); ?>'" style="cursor: pointer;">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhuma associado encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($associados,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listaAssociados')); 
          ?>
        </div>
      </div>


      <script type="text/javascript">
        $(document).ready(function() {
          $("#cpf").mask("999.999.999-99");
        });
      </script>