 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('associadosNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('listaAssociados'); ?>">Associados</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Cadastro de associado</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="progress" id="progresso" style="display: none">
                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                      Carregando...
                    </div>
                  </div>
                  <?php echo $this->partial('form/associado', array('form'=> $formAssociado, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        formInscricao();
        carregarPais(1);
        $("#cpf").blur(function() {
          buscaCliente($("#cpf").val(), 'formAssociado');
        });
      });
    </script>