 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('novaCategoriaTrabalho', array('idEvento' => $idEvento)); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('eventoAlterar', array('id' => $idEvento)); ?>">Evento</a></li>
      <li class="active">Categorias de trabalho</li>
    </ol>
  </div>
    <!-- LISTAGEM DOS CHAMADOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Categorias de trabalho</h3>
            </div>
            <div class="panel-body">
              <?php if($categorias->count() > 0): ?>
                <table class="table">
                  <tr>
                    <th style="text-align: center">Categoria</th>
                    <th style="text-align: center">Deletar</th>
                </tr>
                <?php foreach($categorias as $categoria): ?>
                <tr>
                  <td style="text-align: center"><?= $categoria['categoria']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('deletarCategoriaTrabalho', array('idCategoria' => $categoria['id'])) ?>', 'deletar');">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            <?php else: ?>
              <div class="alert alert-info">Nenhuma categoria de trabalho encontrada!</div>
            <?php endif; ?>
            </div>
          </div>
        </div>
      </div>