<div class="container theme-showcase" role="main">
  <img id="profile-img" class="img-responsive center-block" src="<?= $this->basePath($evento['banner_evento']); ?>" />
  <p id="profile-name" class="profile-name-card"></p>
</div>

<!-- se for cliente não tem filtro -->
<div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                  <form class="form-inline" role="form" method="POST" action="#">

                      <div class="row" style="margin-top:20px;">
                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('autores')->getLabel(); ?></label>
                            <?= 
                              $this->formElement($formPesquisa->get('autores')); 
                              $this->formElement($formPesquisa->get('autores'));
                            ?>
                          </div>
                        </div>

                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('titulo')->getLabel(); ?></label>
                            <?= 
                              $this->formElement($formPesquisa->get('titulo')); 
                              $this->formElement($formPesquisa->get('titulo'));
                            ?>
                          </div>
                        </div>


                      </div>

                      <div class="row" style="margin-top:20px;">
                        <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 20px;">
                        <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                        <button type="submit" name="pesquisar" class="btn btn-success" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                      </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>


    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Trabalhos</li>
      </ol>
    </div>

    <!-- LISTAGEM DOS TRABALHOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de trabalhos</h3>
            </div>
            <div class="panel-body">
              <?php if($trabalhos->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">ID</th>
                  <th style="text-align: center">Categoria</th>
                  <th style="text-align: center">Título</th>
                  <th style="text-align: center">Autores</th>
                  <th style="text-align: center">Status</th>
                  <th style="text-align: center">Visualizar</th>
              </tr>
              <?php foreach($trabalhos as $trabalho): ?>
              <tr>
                <td style="text-align: center"><?= $trabalho['id_trabalho']; ?></td>
                <td style="text-align: center"><?= $trabalho['nome_categoria']; ?></td>
                <td style="text-align: center"><?= $trabalho['titulo_trabalho']; ?></td>
                <td style="text-align: center"><?= $trabalho['nome_completo']; ?></td>
                <td style="text-align: center"><?= $trabalho['trabalho_aprovado'] == 'S' ? 'Aprovado' : 'A aprovar'; ?></td>
                <td style="text-align: center;">
                <?php if(!empty($trabalho['poster'])): ?>
                  <a href="<?= $this->url('downloadArquivoTrabalho', array('idArquivo' => $trabalho['id_trabalho'], 'nomeCampo' => 'poster')); ?>">
                    <img src="<?= $this->basePath('img/download.png'); ?>" title="Download">
                  </a>
                <?php endif; ?>
                  
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
             <div class="alert alert-info">Nenhum trabalho encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($trabalhos,
                                        'Sliding',
                                        'view/paginator', array('route' => 'listarTrabalhosPublic')); 
          ?>
        </div>
      </div>
    <script type="text/javascript">
      $(document).ready(function() {
        var clientes = {
          <?php foreach ($clientes as $cliente) : ?>
            "<?= $cliente['autores'] ?>": "<?= $cliente['autores'] ?>",
          <?php endforeach; ?>
        }
        var clientesArray = $.map(clientes, function (value, key) { return { value: value, data: key }; });

        $('#autores').autocomplete({
          lookup: clientesArray,
          lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
              var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
              return re.test(suggestion.value);
          },
          onSelect: function(suggestion) {
              $('#autores').val(suggestion.data);
          },
          onHint: function (hint) {
              //$('#autocomplete-ajax-x').val(hint);
          },
          onInvalidateSelection: function() {
              //$('#selction-ajax').html('You selected: none');
          }
        });


        var titulos = {
          <?php foreach ($clientes as $trab) : ?>
            "<?= $trab['id_trabalho'] ?>": "<?= $trab['titulo_trabalho'] ?>",
          <?php endforeach; ?>
        }
        var titulosArray = $.map(titulos, function (value, key) { return { value: value, data: key }; });

        $('#titulo').autocomplete({
          lookup: titulosArray,
          lookupFilter: function(suggestion, originalQuery, queryLowerCase) {
              var re = new RegExp('\\b' + $.Autocomplete.utils.escapeRegExChars(queryLowerCase), 'gi');
              return re.test(suggestion.value);
          },
          onSelect: function(suggestion) {
              //$('#titulo').val(suggestion.data);
          },
          onHint: function (hint) {
              //$('#autocomplete-ajax-x').val(hint);
          },
          onInvalidateSelection: function() {
              //$('#selction-ajax').html('You selected: none');
          }
        });

      });
    </script>