<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <?php foreach($avaliacoes as $key => $avaliacao): ?>
    <?php if(!empty($avaliacao['normas'])): ?>
      <a href="<?= $this->url('visualizarAvaliacaoAdminEscrita', array('idAvaliacao' => $avaliacao['id'], 'idInscricao' => $idInscricao)) ?>">
        <button type="button" name="avaliacao<?= $key ?>" class="btn btn-defauolt" style="float: right;margin-right: 10px;">
          <img src="<?php echo $this->basePath('img/avaliador.png') ?>" alt="Deletar trabalho">
          Avaliação <?= $key+1; ?> escrita
        </button>
      </a>
    <?php else: ?>
      <a href="<?= $this->url('visualizarAvaliacaoAdminOral', array('idAvaliacao' => $avaliacao['id'], 'idInscricao' => $idInscricao)) ?>">
        <button type="button" name="avaliacao<?= $key ?>" class="btn btn-defauolt" style="float: right;margin-right: 10px;">
          <img src="<?php echo $this->basePath('img/avaliador.png') ?>" alt="Deletar trabalho">
          Avaliação <?= $key+1; ?> oral
        </button>
      </a>
    <?php endif; ?>  
  <?php endforeach; ?>
  <form name="aprovarTrabalho" action="#" method="POST">
    <?php if($trabalho['trabalho_aprovado'] == 'N'): ?>
      <button type="submit" name="aprovar" class="btn btn-success" style="float: right;margin-right: 10px;">
        <img src="<?php echo $this->basePath('img/trabalho.png') ?>" alt="Aprovar trabalho">
        Aprovar trabalho</button>
    <?php else: ?>
      <button type="submit" name="aprovar" class="btn btn-warning" style="float: right;margin-right: 10px;">
        <img src="<?php echo $this->basePath('img/trabalho.png') ?>" alt="Cancelar aprovação">
        Cancelar aprovação</button>
    <?php endif; ?>
  </form>
  <button type="button" name="deletar" onclick="alerta('<?= $this->url('deletarTrabalho', array('idInscricao' => $idInscricao)); ?>', 'deletar');" class="btn btn-danger" style="float: right;margin-right: 10px;">
    <img src="<?php echo $this->basePath('img/deletar.png') ?>" alt="Deletar trabalho">
    Deletar trabalho
  </button>

  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('listarTrabalhos'); ?>">Trabalhos</a></li>
    <li class="active">Visualizar trabalho</li>
  </ol>
</div>

  <div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Visualizar trabalho</h3>
          </div>
          <div class="panel-body">
              <div class="form-group">
                  <div class="row">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('nome_evento')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('nome_evento')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('nome_evento'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('nome_completo')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('nome_completo')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('nome_completo'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('cpf')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('cpf')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('cpf'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('nome_categoria')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('nome_categoria')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('nome_categoria'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('titulo_trabalho')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('titulo_trabalho')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('titulo_trabalho'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('afiliacao')->getLabel()?></label><br>
                         <?= $this->formElement($formTrabalho->get('afiliacao')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('afiliacao'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('descritor1')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('descritor1')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('descritor1'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('descritor2')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('descritor2')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('descritor2'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('descritor3')->getLabel()?></label><br>
                         <?= $this->formElement($formTrabalho->get('descritor3')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('descritor3'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('autores_trabalho')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('autores_trabalho')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('autores_trabalho'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('apoio_financeiro')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('apoio_financeiro')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('apoio_financeiro'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <?php if(!empty($trabalho['pontuacao'])): ?>
                      <div class='col-sm-4'>
                        <div class="form-group">
                          <label for="disabledTextInput">Pontuação: </label>
                          <input name="pontuacao" type="text" class="form-control" placeholder="" id="pontuacao" value="<?= $trabalho['pontuacao'] ?>" disabled="disabled">
                        </div>
                      </div>
                    <?php endif; ?>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-12'>
                      <label for="disabledTextInput"><?=$formTrabalho->get('resumo_trabalho')->getLabel()?></label><br>
                      <?= $this->formElement($formTrabalho->get('resumo_trabalho')); ?>
                      <?= $this->formElementErrors($formTrabalho->get('resumo_trabalho'), array('class' => 'alert alert-danger')); ?>
                    </div>
                  </div>
          </div>
        </div>
    </div>
  </div>
  </div>

  <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Arquivos vinculados</h3>
            </div>
            <div class="panel-body">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Arquivo</th>
                </tr>
                <tr <?php if (isset($trabalho->comite_etica)) : ?>>
                  <td style="text-align: center"><a href="<?= $this->url('downloadArquivoTrabalho', array('idArquivo' => $trabalho->id_trabalho, 'nomeCampo' => 'comite_etica')); ?>">Cópia do parecer (CEP, PROSPERO ou TCLE)</a></td>
                </tr <?php endif; ?>>
                
                <tr >
                  <td style="text-align: center">
                  Os vídeos enviados para o processo seletivo poderão ser postados em nossas redes sociais?
                  <b><?php echo $trabalho->pode_postar == 'S' ? 'Sim' : 'Não' ?></b>
                  </td>
                </tr>
                
                <tr <?php if (isset($trabalho->stricto_sensu)) : ?>>
                  <td style="text-align: center"><a href="<?= $this->url('downloadArquivoTrabalho', array('idArquivo' => $trabalho->id_trabalho, 'nomeCampo' => 'stricto_sensu')); ?>">Stricto sensu - Comprovante de matrícula atualizado (últimos 3 meses)</a></td>
                </tr <?php endif; ?>>

                <tr <?php if (isset($trabalho->mestrado_doutorado)) : ?>>
                  <td style="text-align: center"><a href="<?= $this->url('downloadArquivoTrabalho', array('idArquivo' => $trabalho->id_trabalho, 'nomeCampo' => 'mestrado_doutorado')); ?>">Mestrado ou Doutorado - Certificado ou ata de defesa de mestrado ou doutorado, ou diploma de mestrado/doutorado</a></td>
                </tr <?php endif; ?>>
                
                <tr>
                <td style="text-align: center">
                  <a href="<?= $trabalho->link_video ?>" target="_blank">Link do vídeo</a>
                </td>
                </tr>

                <?php if(!empty($trabalho['poster'])): ?>
                  <tr>
                    <td style="text-align: center"><a href="<?= $this->url('downloadArquivoTrabalho', array('idArquivo' => $trabalho->id_trabalho, 'nomeCampo' => 'poster')); ?>">Pôster</a></td>
                  </tr>
                <?php endif; ?>
              </table>
            </div>
          </div>
        </div>
      </div>

    <script type="text/javascript">

      $(document).ready(function() {
        $('#nome_evento').attr('disabled', 'disabled');
        $('#nome_completo').attr('disabled', 'disabled');
        $('#cpf').attr('disabled', 'disabled');
        $('#nome_categoria').attr('disabled', 'disabled');
        $('#titulo_trabalho').attr('disabled', 'disabled');
        $('#autores_trabalho').attr('disabled', 'disabled');
        $('#resumo_trabalho').attr('disabled', 'disabled');

        $('#afiliacao').attr('disabled', 'disabled');
        $('#descritor1').attr('disabled', 'disabled');
        $('#descritor2').attr('disabled', 'disabled');
        $('#descritor3').attr('disabled', 'disabled');
        $('#apoio_financeiro').attr('disabled', 'disabled');

        CKEDITOR.replace('resumo_trabalho');
      });
    </script>