 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    
    <a  href="<?= $this->url('downloadCertificadoCategoriaAssociado', array('idCategoria' => $categoria['id'])) ?>">                  
      <button type="button" class="btn btn-success" style="float: right;margin-right: 5px;">
      <img src="<?php echo $this->basePath('img/download.png') ?>" alt="Download do certificado">
      Download do certificado</button>
    </a>
 
 
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('home'); ?>">Home</a></li>
    <li><a href="<?= $this->url('categoriaAssociadosAlterar', array('idCategoria' => $categoria['id'])); ?>">Categoria de associado</a></li>
    <li class="active">Configurar certificado</li>
  </ol>
</div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Configurar certificado do grupo: <?= $categoria->nome ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formConfigurar, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>

    <!-- LISTAGEM DE CAMPOS -->
    <?php if(!$configuracoes || $configuracoes->count() == 0): ?>
      <div class="container theme-showcase" role="main">
        <div class="row">
          <div class="alert alert-info">Nenhuma configuração vinculada!</div>
        </div>
      </div>
    <?php else: ?>

     <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Configurações vinculadas</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">Campo</th>
                  <th style="text-align: center">Cor</th>
                  <th style="text-align: center">Posição de início X</th>
                  <th style="text-align: center">Posição de início Y</th>
                  <th style="text-align: center">Tamanho da fonte</th>
                  <th style="text-align: center">Centralizar</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach ($configuracoes as $configuracao): ?>
              <tr>
                <td style="text-align: center"><?= $configuracao->nome_campo; ?></td>
                <td style="text-align: center"><?= $configuracao->cor ?></td>
                <td style="text-align: center"><?= $configuracao->posicao_x ?></td>
                <td style="text-align: center"><?= $configuracao->posicao_y ?></td>
                <td style="text-align: center"><?= $configuracao->tamanho_fonte ?></td>
                <td style="text-align: center"><?= $this->simNao($configuracao->centralizar); ?></td>
                <td style="text-align: center">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('configurarCertificadoAssociado', array('idCategoria' => $categoria->id, 'certificado' => $configuracao->id)); ?>'" style="cursor: pointer;">
                    <span style="margin-right:4px;"></span> 
                  <img src="<?php echo $this->basePath('img/deletar.png') ?>" onclick="alerta('<?= $this->url('deletarConfiguracaoAssociado', array('id' => $configuracao->id, 'idCategoria' => $categoria->id)); ?>', 'deletar');" title="Deletar">
                </td>
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>