<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'associado' => $associado,
          'pagina' => 'anuidades'
        )
      );
      ?>
    </div>
    
    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-warning">
          <div class="panel-heading">
            <h3 class="panel-title">Minhas anuidades</h3>
          </div>
          <div class="panel-body">
            <?php if ($anuidades->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Anuidade</th>
                    <th style="text-align: center">Período de referência</th>
                    <th style="text-align: center">Vencimento</th>
                    <th style="text-align: center">Valor</th>
                    <th style="text-align: center">Valor pago</th>
                    <th style="text-align: center">Status</th>
                    <th style="text-align: center">Ações</th>
                  </tr>
                  <?php foreach ($anuidades as $anuidade) : ?>
                    <tr>
                      <td style="text-align: center"><?= $anuidade['nome_fantasia']; ?></td>
                      <td style="text-align: center"><?= $anuidade['descricao_anuidade']; ?></td>
                      <td style="text-align: center"><?= $this->converterData($anuidade['data_inicio']); ?> a <?= $this->converterData($anuidade['data_fim']); ?></td>
                      <td style="text-align: center"><?= $this->converterData($anuidade['data_vencimento']); ?></td>
                      <td style="text-align: center"><?= $this->exibirMonetario($anuidade['valor_anuidade']); ?></td>
                      <td style="text-align: center"><?= $this->caracterVazio($this->exibirMonetario($anuidade['valor_pagamento'])); ?></td>
                      <?php if (empty($anuidade['data_pagamento'])) : ?>
                        <td style="text-align: center">Inadimplente</td>
                      <?php else : ?>
                        <td style="text-align: center">Adimplente</td>
                      <?php endif; ?>

                      <td style="text-align: center;">
                        <img src="<?= $this->basePath('img/money.png'); ?>" onclick="$.colorbox({href:'<?= $this->url('pagarAnuidadeCliente', array('associado' => $anuidade['id_associado'], 'anuidade' => $anuidade['id_anuidade'])); ?>'});" title="Pagar anuidade" style="cursor: pointer;">
                        <span style="margin-right:4px;"></span>
                        <?php if (empty($anuidade['data_hora_comprovante'])) : ?>
                          <?php $img = 'img/upload.png'; ?>
                        <?php else : ?>
                          <?php $img = 'img/uploadok.png'; ?>
                        <?php endif; ?>
                        <a href="<?= $this->url('uploadComprovanteAnuidade', array('idAnuidade' => $anuidade['id_anuidade'])) ?>">
                          <img src="<?= $this->basePath($img); ?>" title="Upload de comprovante">
                        </a>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhuma anuidade encontrada!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>
      <div style="float:right;">
        <?php echo $this->paginationControl(
          $anuidades,
          'Sliding',
          'view/paginator',
          array('route' => 'anuidadesCliente')
        );
        ?>
      </div>
    </div>

  </div>
</div>