<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'associado' => $associado,
          'pagina' => 'arquivos'
        )
      );
      ?>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-info">
          <div class="panel-heading">
            <h3 class="panel-title">Meus arquivos</h3>
          </div>
          <div class="panel-body">
            <?php if ($arquivos->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Categoria de associado</th>
                    <th style="text-align: center">Arquivo</th>
                    <th style="text-align: center">Ações</th>
                  </tr>
                  <?php
                  foreach ($arquivos as $arquivo) : ?>
                    <?php
                    if (
                      ($arquivo['status_associado'] == 'T')
                      ||
                      ($arquivo['status_associado'] == 'A' && $arquivo['exibir_site'] == 'S')
                      ||
                      ($arquivo['status_associado'] == 'I' && $arquivo['exibir_site'] == 'N')
                    ) : ?>

                      <tr>
                        <td style="text-align: center"><?= $arquivo['nome_fantasia']; ?></td>
                        <td style="text-align: center"><?= $arquivo['nome_categoria']; ?></td>
                        <td style="text-align: center"><?= $arquivo['descricao_arquivo']; ?></td>
                        <td style="text-align: center;">
                          <?php if ($arquivo['nome_fantasia'] == '-') : ?>
                            <a href="<?= $this->url('downloadArquivoIndividual', array('idArquivo' => $arquivo['id_arquivo'])) ?>">
                              <img src="<?= $this->basePath('img/download.png'); ?>" title="Editar" style="cursor: pointer;">
                            </a>
                          <?php else : ?>
                            <a href="<?= $this->url('downloadArquivoAssociado', array('idArquivo' => $arquivo['id_arquivo'])) ?>">
                              <img src="<?= $this->basePath('img/download.png'); ?>" title="Editar" style="cursor: pointer;">
                            </a>
                          <?php endif; ?>
                        </td>
                      </tr>
                    <?php endif; ?>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhum arquivo encontrado!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>

      <div style="float:right;">
        <?php echo $this->paginationControl(
          $arquivos,
          'Sliding',
          'view/paginator',
          array('route' => 'arquivosCliente')
        );
        ?>
      </div>

    </div>

  </div>
</div>