<?php if($erroPDF): ?>
<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="alert alert-info" role="alert">
      Favor enviar arquivo(s) no formato PDF!
    </div>
  </div>
</div>
<?php endif; ?>
<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('inscricoesCliente'); ?>">Inscrições</a></li>
    <li class="active">Enviar trabalho</li>
  </ol>
</div>
  <div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-success">
        <div class="panel-heading">
            <h3 class="panel-title">Enviar trabalho</h3>
          </div>
          <div class="panel-body">
              <div class="form-group">
                <form name="frmTrabalho" class="form-inline" method="POST" action="#" enctype='multipart/form-data'>
                  <div class="row">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('categoria')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('categoria')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('categoria'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('titulo')->getLabel()?></label>
                         <?= $this->formElement($formTrabalho->get('titulo')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('titulo'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>

                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('autores')->getLabel()?></label><br>
                         <?= $this->formElement($formTrabalho->get('autores')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('autores'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-4'>
                      <div class="form-group">
                         <label for="disabledTextInput"><?=$formTrabalho->get('arquivos')->getLabel()?></label><br>
                         <?= $this->formElement($formTrabalho->get('arquivos')); ?>
                         <?= $this->formElementErrors($formTrabalho->get('arquivos'), array('class' => 'alert alert-danger')); ?>
                      </div>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-12'>
                      <label for="disabledTextInput"><?=$formTrabalho->get('resumo')->getLabel()?></label><br>
                      <?= $this->formElement($formTrabalho->get('resumo')); ?>
                      <?= $this->formElementErrors($formTrabalho->get('resumo'), array('class' => 'alert alert-danger')); ?>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                      <img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
                      Salvar
                    </button>
                  </div>
                </form>
          </div>
        </div>
    </div>
  </div>
  </div>

    <script type="text/javascript">
      CKEDITOR.replace('resumo');
    </script>