<div class="container theme-showcase" role="main">
  

    <?php if (is_array($trabalhos) && count($trabalhos) > 0) : ?>
      <div class="row">
        <div class="col-md-12">
          <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('listaTrabalhosAvaliador'); ?>'" style="float: right;margin-bottom: 10px">
            <img src="<?php echo $this->basePath('img/avaliador.png') ?>" alt="Avaliar trabalhos">
            Avaliar trabalhos
          </button>
        </div>
      </div>
    <?php endif; ?>

    <div class="row">
      <div class="col-md-3">
        <?php echo $this->partial('menu/cliente', 
          array(
            'associado' => $associado, 
            'questionario' => $questionario, 
            'associado' => $associado,
            'pagina' => 'inscricoes'
          ));
        ?>
      </div>

    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-success">
          <div class="panel-heading">
            <h3 class="panel-title">Minhas inscrições</h3>
          </div>
          <div class="panel-body">
            <?php if ($inscricoes->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Evento</th>
                    <th style="text-align: center">Status do pagamento</th>
                    <th style="text-align: center">CPF</th>
                    <th style="text-align: center">Categoria de inscrição</th>
                    <th style="text-align: center">Ações</th>
                  </tr>
                  <?php foreach ($inscricoes as $inscricao) : ?>
                    <tr>
                      <td style="text-align: center"><?= $inscricao['nome_fantasia']; ?></td>
                      <td style="text-align: center"><?= $inscricao['sigla']; ?> - <?= $inscricao['nome_evento'] ?></td>
                      <td style="text-align: center"><?= $this->caracterVazio($inscricao['nome_status_pagamento']); ?></td>
                      <td style="text-align: center"><?= $inscricao['cpf']; ?>
                        <?php if (!empty($inscricao['cnpj'])) {
                          echo ' / ' . $inscricao['cnpj'];
                        }
                        ?>
                      </td>
                      <td style="text-align: center"><?= $inscricao['nome_categoria']; ?></td>
                      <td style="text-align: center;">
                        <img src="<?= $this->basePath('img/editar.png'); ?>" onclick="location.href='<?= $this->url('gerenciarInscricao', array('id' => $inscricao['id'])); ?>'" title="Editar" style="cursor: pointer;">
                        <span style="margin-right:4px;"></span>
                        <?php if (empty($inscricao['comprovante'])) : ?>
                          <?php $img = 'img/upload.png'; ?>
                        <?php else : ?>
                          <?php $img = 'img/uploadok.png'; ?>
                        <?php endif; ?>
                        <a href="<?= $this->url('comprovanteInscricao', array('idInscricao' => $inscricao['id'])) ?>">
                          <img src="<?= $this->basePath($img); ?>" title="Upload de comprovante">
                        </a>

                        <?php if ($inscricao['enviar_trabalho'] == 'S' && ($inscricao['status_pagamento'] == 2 || $inscricao['status_pagamento'] == 8 || $inscricao['status_pagamento'] == 9)) : ?>
                          <span style="margin-right:4px;"></span>
                          <?php if (empty($inscricao['categoria_trabalho'])) : ?>
                            <a href="<?= $this->url('enviarTrabalho', array('idInscricao' => $inscricao['id'])) ?>">
                              <img src="<?= $this->basePath('img/trabalho.png'); ?>" title="Enviar trabalho">
                            </a>
                          <?php else : ?>
                            <?php if (empty($inscricao['poster']) && $inscricao['trabalho_aprovado'] == 'S') : ?>
                              <a href="<?= $this->url('vincularPosterTrabalho', array('idInscricao' => $inscricao['id'])) ?>">
                                <img src="<?= $this->basePath('img/trabalho.png'); ?>" title="Enviar poster">
                              </a>
                            <?php endif; ?>
                          <?php endif; ?>
                        <?php endif; ?>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhuma inscrição encontrada!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>

      <div style="float:right;">
        <?php echo $this->paginationControl(
          $inscricoes,
          'Sliding',
          'view/paginator',
          array('route' => 'inscricoesCliente')
        );
        ?>
      </div>
    </div>






  </div>
</div>