<div class="container theme-showcase" role="main">
  <div class="row">

    <ul class="nav nav-tabs">
      <li class="active">
        <a style="background-color:#dff0d8;margin-right: 0px;">
          <img src="<?= $this->basePath('img/inscricao.png') ?>"> Inscrições
        </a>
      </li>
      <?php if($associado && $associado['ativo'] == 'S'): ?>
        <li>
          <a style="background-color:#fcf8e3;margin-right: 0px;" href="<?= $this->url('anuidadesCliente'); ?>">
            <img src="<?= $this->basePath('img/agendado.png') ?>"> Anuidades
          </a>
        </li>
        <li><a style="background-color:#d9edf7;margin-right: 0px;" href="<?= $this->url('arquivosCliente'); ?>">
          <img src="<?= $this->basePath('img/visualizar.png') ?>"> Arquivos
        </a>
        </li>
        <li><a style="background-color:#f8d7da;margin-right: 0px;" href="<?= $this->url('questionariosCliente'); ?>">
          <img src="<?= $this->basePath('img/msg.png') ?>"> Questionários/pesquisas
        </a>
        </li>

        <?php if($questionario): ?>
          <button type="button" class="btn btn-danger" onclick="$.colorbox({href:'<?= $this->url('responderQuestionarioAssociado', array('idQuestionario' => $questionario['id'])); ?>'});" style="float: right;">
              <img src="<?php echo $this->basePath('img/msg.png') ?>" alt="Novo">
              Responder questionário/pesquisa
          </button>
        <?php endif; ?>
      <?php endif; ?>
      <li>
        <a style="background-color:#FFF5EE;margin-right: 0px;" href="<?= $this->url('listarTransmissoes'); ?>">
          <img src="<?= $this->basePath('img/transmissao.png') ?>"> Transmissões
        </a>
      </li>
      <li>
        <a style="background-color:#ebebeb;margin-right: 0px;" href="<?= $this->url('meusDadosCliente'); ?>">
          <img src="<?= $this->basePath('img/usuario.png') ?>"> Meus dados
        </a>
      </li>
      
      <?php if(!empty($associado->certificado)): ?>
      <li>
        <a style="background-color:#007bff;margin-right: 0px;" href="<?= $this->url('downloadCertificadoCategoriaAssociado', array('idCategoria' => $associado->id_categoria)) ?>">
          <img src="<?= $this->basePath('img/download.png') ?>"> Certificado
        </a>
      </li>
      <?php endif; ?>

    </ul>
    
    
      


  </div>
</div>


    <!-- LISTAGEM DOS EVENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Minhas inscrições</h3>
            </div>
            <div class="panel-body">
              <?php if($inscricoes->count() > 0): ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Empresa</th>
                    <th style="text-align: center">Evento</th>
                    <th style="text-align: center">Status do pagamento</th>
                    <th style="text-align: center">CPF</th>
                    <th style="text-align: center">Categoria de inscrição</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($inscricoes as $inscricao): ?>
                <tr>
                  <td style="text-align: center"><?= $inscricao['nome_fantasia']; ?></td>
                  <td style="text-align: center"><?= $inscricao['sigla']; ?> - <?= $inscricao['nome_evento'] ?></td>
                  <td style="text-align: center"><?= $this->caracterVazio($inscricao['nome_status_pagamento']); ?></td>
                  <td style="text-align: center"><?= $inscricao['cpf']; ?>
                    <?php if(!empty($inscricao['cnpj'])){
                            echo ' / '.$inscricao['cnpj'];
                          } 
                    ?>
                  </td>
                  <td style="text-align: center"><?= $inscricao['nome_categoria']; ?></td>
                  <td style="text-align: center;">
                    <img src="<?= $this->basePath('img/editar.png'); ?>" onclick="location.href='<?= $this->url('gerenciarInscricao', array('id' => $inscricao['id'])); ?>'" title="Editar"  style="cursor: pointer;">
                    <span style="margin-right:4px;"></span>
                    <?php if(empty($inscricao['comprovante'])): ?>
                      <?php $img = 'img/upload.png'; ?>
                    <?php else: ?>
                      <?php $img = 'img/uploadok.png'; ?>
                    <?php endif; ?>
                    <a href="<?= $this->url('comprovanteInscricao', array('idInscricao' => $inscricao['id'])) ?>">
                      <img src="<?= $this->basePath($img); ?>" title="Upload de comprovante">
                    </a>

                    <?php if($inscricao['enviar_trabalho'] == 'S' && ($inscricao['status_pagamento'] == 2 || $inscricao['status_pagamento'] == 8 || $inscricao['status_pagamento'] == 9)): ?>
                      <span style="margin-right:4px;"></span>
                      <?php if(empty($inscricao['categoria_trabalho'])): ?>
                        <a href="<?= $this->url('enviarTrabalho', array('idInscricao' => $inscricao['id'])) ?>">
                          <img src="<?= $this->basePath('img/trabalho.png'); ?>" title="Enviar trabalho">
                        </a>
                      <?php else: ?>
                          <img src="<?= $this->basePath('img/trabalho.png'); ?>" title="Trabalho enviado" onclick="alert('Seu trabalho já foi enviado!');" style="cursor:pointer;">
                      <?php endif; ?>
                    <?php endif; ?>
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            </div>
          <?php else: ?>
             <div class="alert alert-info">Nenhuma inscrição encontrada!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($inscricoes,
                                        'Sliding',
                                        'view/paginator', array('route' => 'inscricoesCliente')); 
          ?>
        </div>
      </div>
