<div class="container theme-showcase" role="main">
  <div class="row">

    <ul class="nav nav-tabs">
      <li class="active">
        <a style="background-color:#dff0d8;margin-right: 0px;"  href="<?= $this->url('inscricoesCliente'); ?>">
          <img src="<?= $this->basePath('img/inscricao.png') ?>"> Inscrições
        </a>
      </li>
      <?php if($associado && $associado['ativo'] == 'S'): ?>
        <li>
          <a style="background-color:#fcf8e3;margin-right: 0px;" href="<?= $this->url('anuidadesCliente'); ?>">
            <img src="<?= $this->basePath('img/agendado.png') ?>"> Anuidades
          </a>
        </li>
        <li><a style="background-color:#d9edf7;margin-right: 0px;" href="<?= $this->url('arquivosCliente'); ?>">
          <img src="<?= $this->basePath('img/visualizar.png') ?>"> Arquivos
        </a>
        </li>
        <li><a style="background-color:#f8d7da;margin-right: 0px;" href="<?= $this->url('questionariosCliente'); ?>">
          <img src="<?= $this->basePath('img/msg.png') ?>"> Questionários/pesquisas
        </a>
        </li>

        <?php if($questionario): ?>
          <button type="button" class="btn btn-danger" onclick="$.colorbox({href:'<?= $this->url('responderQuestionarioAssociado', array('idQuestionario' => $questionario['id'])); ?>'});" style="float: right;">
              <img src="<?php echo $this->basePath('img/msg.png') ?>" alt="Novo">
              Responder questionário/pesquisa
          </button>
        <?php endif; ?>
      <?php endif; ?>
      <li>
        <a style="background-color:#FFF5EE;margin-right: 0px;">
          <img src="<?= $this->basePath('img/transmissao.png') ?>"> Transmissões
        </a>
      </li>
      <li>
        <a style="background-color:#ebebeb;margin-right: 0px;" href="<?= $this->url('meusDadosCliente'); ?>">
          <img src="<?= $this->basePath('img/usuario.png') ?>"> Meus dados
        </a>
      </li>

      <?php if(!empty($associado->certificado)): ?>
      <li>
        <a style="background-color:#007bff;margin-right: 0px;" href="<?= $this->url('downloadCertificadoCategoriaAssociado', array('idCategoria' => $associado->id_categoria)) ?>">
          <img src="<?= $this->basePath('img/download.png') ?>"> Certificado
        </a>
      </li>
      <?php endif; ?>
    </ul>
    

  </div>
</div>


    <!-- LISTAGEM DOS EVENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Transmissões em aberto</h3>
            </div>
            <div class="panel-body">
              <?php if($transmissoes->count() > 0): ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Evento</th>
                    <th style="text-align: center">Sala</th>
                    <th style="text-align: center">Descrição</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Assistir</th>
                </tr>
                <?php foreach($transmissoes as $transmissao): ?>
                <tr>
                  <td style="text-align: center"><?= $transmissao['nome_evento']; ?></td>
                  <td style="text-align: center"><?= $transmissao['sala']; ?></td>
                  <td style="text-align: center"><?= $transmissao['descricao_transmissao']; ?></td>
                  <td style="text-align: center"><?= $this->converterData($transmissao['inicio_transmissao']); ?></td>
                  <td style="text-align: center"><?= $this->converterData($transmissao['fim_transmissao']); ?></td>
                  <td style="text-align: center;">
                    <a href="<?= $this->url('visualizarTransmissao', array('transmissao' => $transmissao['id_transmissao'])); ?>" target="_blank">  
                      <img src="<?= $this->basePath('img/visualizar.png'); ?>" title="Visualizar"  style="cursor: pointer;">
                    </a>
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            </div>
          <?php else: ?>
             <div class="alert alert-info">Nenhuma transmissão encontrada!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>