<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'associado' => $associado,
          'pagina' => 'transmissoes'
        )
      );
      ?>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Transmissões em aberto</h3>
          </div>
          <div class="panel-body">
            <?php if ($transmissoes->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Evento</th>
                    <th style="text-align: center">Sala</th>
                    <th style="text-align: center">Descrição</th>
                    <th style="text-align: center">Início</th>
                    <th style="text-align: center">Fim</th>
                    <th style="text-align: center">Assistir</th>
                  </tr>
                  <?php foreach ($transmissoes as $transmissao) : ?>
                    <tr>
                      <td style="text-align: center"><?= $transmissao['nome_evento']; ?></td>
                      <td style="text-align: center"><?= $transmissao['sala']; ?></td>
                      <td style="text-align: center"><?= $transmissao['descricao_transmissao']; ?></td>
                      <td style="text-align: center"><?= $this->converterData($transmissao['inicio_transmissao']); ?></td>
                      <td style="text-align: center"><?= $this->converterData($transmissao['fim_transmissao']); ?></td>
                      <td style="text-align: center;">
                        <a href="<?= $this->url('visualizarTransmissao', array('transmissao' => $transmissao['id_transmissao'])); ?>" target="_blank">
                          <img src="<?= $this->basePath('img/visualizar.png'); ?>" title="Visualizar" style="cursor: pointer;">
                        </a>
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhuma transmissão encontrada!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>