<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'associado' => $associado,
          'pagina' => 'transmissoes'
        )
      );
      ?>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h3 class="panel-title">Vídeos por evento</h3>
          </div>
          <div class="panel-body">
            <?php if ($videos->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Evento</th>
                    <th style="text-align: center">Assistir</th>
                  </tr>
                  <?php foreach ($videos as $video) : ?>
                    <tr>
                      <td style="text-align: center"><?= $video['sigla']; ?> - <?= $video['nome_evento']; ?></td>
                      <td style="text-align: center;">
                        <img src="<?= $this->basePath('img/transmissao.png'); ?>" 
                          onclick="$.colorbox({
                            href:'<?= $this->url('visualizarVideo', array('evento' => $video['id_evento'])); ?>',
                            width: '100%',
                            height: '100%',
                            maxWidth: '100%',
                            maxHeight: '100%',
                            scrolling: false
                          });" title="Visualizar" style="cursor: pointer;">
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhum vídeo encontrado!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>