 <div class="container theme-showcase" role="main">
   <div class="row">

     <div class="col-md-3">
       <?php echo $this->partial(
          'menu/cliente',
          array(
            'associado' => $associado,
            'questionario' => $questionario,
            'associado' => $associado,
            'pagina' => 'meus-dados'
          )
        );
        ?>
     </div>

     <div class="col-md-9">
       <div class="row">
         <div class="panel panel-default">
           <div class="panel-heading">
             <h3 class="panel-title">Alterar associado</h3>
           </div>
           <div class="panel-body">
             <div class="form-group">
               <?php echo $this->partial('form/associado', array('form' => $formCliente, 'route' => '')) ?>

             </div>
           </div>
         </div>
       </div>
     </div>

   </div>
 </div>



 <script type="text/javascript">
   $(document).ready(function() {
     formInscricao();
     carregarPais(<?= $cliente['pais_endereco'] ?>);
     $('#cpf').attr('disabled', 'disabled');
     $('#email').attr('disabled', 'disabled');
   });
 </script>