<div class="container theme-showcase" role="main">
  <div class="row">
    <ul class="nav nav-tabs">
      <li>
        <a style="background-color:#dff0d8;margin-right: 0px;"  href="<?= $this->url('inscricoesCliente'); ?>">
          <img src="<?= $this->basePath('img/inscricao.png') ?>"> Inscrições
        </a>
      </li>
      <?php if($associado && $associado['ativo'] == 'S'): ?>
        <li>
          <a style="background-color:#fcf8e3;margin-right: 0px;" href="<?= $this->url('anuidadesCliente'); ?>">
            <img src="<?= $this->basePath('img/agendado.png') ?>"> Anuidades
          </a>
        </li>
        <li><a style="background-color:#d9edf7;margin-right: 0px;" href="<?= $this->url('arquivosCliente'); ?>">
          <img src="<?= $this->basePath('img/visualizar.png') ?>"> Arquivos
        </a>
        </li>
        <li class="active"><a style="background-color:#f8d7da;margin-right: 0px;">
          <img src="<?= $this->basePath('img/msg.png') ?>"> Questionários/pesquisas
        </a>
        </li>

        <?php if($questionario): ?>
          <button type="button" class="btn btn-danger" onclick="$.colorbox({href:'<?= $this->url('responderQuestionarioAssociado', array('idQuestionario' => $questionario['id'])); ?>'});" style="float: right;">
              <img src="<?php echo $this->basePath('img/msg.png') ?>" alt="Novo">
              Responder questionário/pesquisa
          </button>
        <?php endif; ?>
      <?php endif; ?>
      <li>
        <a style="background-color:#FFF5EE;margin-right: 0px;" href="<?= $this->url('listarTransmissoes'); ?>">
          <img src="<?= $this->basePath('img/transmissao.png') ?>"> Transmissões
        </a>
      </li>
      <li>
        <a style="background-color:#ebebeb;margin-right: 0px;" href="<?= $this->url('meusDadosCliente'); ?>">
          <img src="<?= $this->basePath('img/usuario.png') ?>"> Meus dados
        </a>
      </li>

      <?php if(!empty($associado->certificado)): ?>
      <li>
        <a style="background-color:#007bff;margin-right: 0px;" href="<?= $this->url('downloadCertificadoCategoriaAssociado', array('idCategoria' => $associado->id_categoria)) ?>">
          <img src="<?= $this->basePath('img/download.png') ?>"> Certificado
        </a>
      </li>
      <?php endif; ?>
    </ul>




  </div>
</div>

    <!-- LISTAGEM DOS EVENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-danger">
            <div class="panel-heading">
              <h3 class="panel-title">Questionários/pesquisas respondidas</h3>
            </div>
            <div class="panel-body">
              <?php if($questionarios->count() > 0): ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome</th>
                    <th style="text-align: center">Período</th>
                    <th style="text-align: center">Ações</th>
                </tr>
                <?php foreach($questionarios as $questionario): ?>
                <tr>
                  <td style="text-align: center"><?= $questionario['nome']; ?></td>
                  <td style="text-align: center"><?= $this->converterData($questionario['data_inicio']); ?> a <?= $this->converterData($questionario['data_fim']); ?></td>
                  <td style="text-align: center;">
                      <img onclick="visualizarQuestionario('<?= $this->url('visualizarQuestionarioCliente', array('id' => $questionario['id_resposta'])) ?>');" src="<?= $this->basePath('img/visualizar.png'); ?>" title="Editar"  style="cursor: pointer;">
                  </td>
                </tr>
                <?php endforeach; ?>
              </table>
            </div>
          <?php else: ?>
             <div class="alert alert-info">Nenhum questionário/pesquisa encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($questionarios,
                                        'Sliding',
                                        'view/paginator', array('route' => 'questionariosCliente')); 
          ?>
        </div>
      </div>

      <script type="text/javascript">
          function visualizarQuestionario(url){
            $.colorbox({href:url});
          }

      </script>