<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'associado' => $associado,
          'pagina' => 'questionario'
        )
      );
      ?>
    </div>

    <div class="col-md-9">
      <div class="row">
        <div class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title">Questionários/pesquisas respondidas</h3>
          </div>
          <div class="panel-body">
            <?php if ($questionarios->count() > 0) : ?>
              <div class="table-responsive">
                <table class="table">
                  <tr>
                    <th style="text-align: center">Nome</th>
                    <th style="text-align: center">Período</th>
                    <th style="text-align: center">Ações</th>
                  </tr>
                  <?php foreach ($questionarios as $questionario) : ?>
                    <tr>
                      <td style="text-align: center"><?= $questionario['nome']; ?></td>
                      <td style="text-align: center"><?= $this->converterData($questionario['data_inicio']); ?> a <?= $this->converterData($questionario['data_fim']); ?></td>
                      <td style="text-align: center;">
                        <img onclick="visualizarQuestionario('<?= $this->url('visualizarQuestionarioCliente', array('id' => $questionario['id_resposta'])) ?>');" src="<?= $this->basePath('img/visualizar.png'); ?>" title="Editar" style="cursor: pointer;">
                      </td>
                    </tr>
                  <?php endforeach; ?>
                </table>
              </div>
            <?php else : ?>
              <div class="alert alert-info">Nenhum questionário/pesquisa encontrado!</div>
            <?php endif; ?>
          </div>
        </div>
      </div>

      <div style="float:right;">
        <?php echo $this->paginationControl(
          $questionarios,
          'Sliding',
          'view/paginator',
          array('route' => 'questionariosCliente')
        );
        ?>
      </div>
    </div>

  </div>
</div>


<script type="text/javascript">
  function visualizarQuestionario(url) {
    $.colorbox({
      href: url
    });
  }
</script>