 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <?php if($comprovante): ?>
      <a href="<?= $this->url('downloadComprovanteAssociado', array('id' => $comprovante['id'])); ?>">
        <button type="button" class="btn btn-success" style="float: right;">
        <img src="<?php echo $this->basePath('img/download.png') ?>" alt="Novo">
        Download do comprovante</button>
      </a>
    <?php endif; ?>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <?php if($usuario['id_usuario_tipo'] == 1): ?>
        <li><a href="<?= $this->url('listaPagamentosAssociados'); ?>">Anuidades</a></li>
      <?php else: ?>
        <li><a href="<?= $this->url('anuidadesCliente'); ?>">Anuidades</a></li>
      <?php endif; ?>
      <li class="active">Upload de comprovante</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Upload de comprovante: <?= $anuidade['descricao'] ?> </h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formArquivo, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        formInscricao();
        $("#cpf").blur(function() {
          buscaCliente($("#cpf").val(), 'formAssociado');
        });
      });
    </script>