    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('categoriaAssociadosNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

      <a href="<?= $this->url('mensagemAssociado'); ?>">
        <button type="button" class="btn btn-info" style="float: right;margin-right: 10px;">
        <img src="<?php echo $this->basePath('img/msg.png') ?>" alt="Enviar mensagem">
        Enviar mensagem</button>
      </a>

      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Categorias de associados</li>
      </ol>
    </div>
    <!-- LISTAGEM DOS EQUIPAMENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de categorias</h3>
            </div>
            <div class="panel-body">
              <?php if($categorias->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Empresa</th>
                  <th style="text-align: center">Nome da categoria</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($categorias as $categoria): ?>
              <tr>
                <td style="text-align: center"><?= $categoria['nome_fantasia']; ?></td>
                <td style="text-align: center"><?= $categoria['nome']; ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                  onclick="location.href='<?= $this->url('categoriaAssociadosAlterar', array('idCategoria' => $categoria['id'])); ?>'" style="cursor: pointer;">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhuma categoria encontrada!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($categorias,
                                        'Sliding',
                                        'view/paginator', array('route' => 'empresa')); 
          ?>
        </div>
      </div>