<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('home'); ?>">Home</a></li>
    <li><a href="<?= $this->url('listaCategoriaAssociados'); ?>">Categorias de associados</a></li>
    <li class="active">Mensagem para associados</li>
  </ol>
</div>

<?php if(count($erros) > 0 || count($listaEmail['contatos']) > 0): ?>
<div class="container theme-showcase" role="main">
  <div class="alert alert-warning" role="alert">
    <b>Total de associados: </b> <?= count($listaEmail['contatos']); ?><br>
    <b>Endereços inválidos: </b><br>
    <?php foreach ($erros as $cpf => $email): ?>
      Email <?= $email ?>, cpf: <?= $cpf ?><br>
    <?php endforeach; ?>
  </div>
</div>
<?php endif; ?>

<?php if($listaEmail != false): ?>
<div class="container theme-showcase" role="main">
  <div class="panel panel-success">
    <div class="panel-heading">
      <h3 class="panel-title">Enviar mensagem</h3>
    </div>
    <div class="panel-body">
      <div class="form-group">
          <div class="row">
            <div class="col-sm-12">
               <div class="progress">
                  <div class="progress-bar" role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" id="progressbar" style="width:0%">
                    <span class="sr-only">70% Complete</span>
                  </div>
                </div> 
            </div>
          </div>

        <div class="row" style="margin-top:20px;">
          <button type="button" class="btn btn-success" id="botao_enviar" onclick="enviarEmail();" style="float: right;margin-right: 10px;">
            <img src="<?php echo $this->basePath('img/enviar.png') ?>" alt="Salvar">
            Enviar mensagens
          </button>
        </div>

      </div>
    </div>
  </div>
</div>

<script type="text/javascript">
  function enviarEmail(){
    $('#botao_enviar').prop('disabled', true);
    dadosEmail = <?= json_encode($listaEmail); ?>;
    for(var x=0; x < dadosEmail.requests.length; x++){      
      //alert(dadosEmail.requests[x].min);
      var data = {dados: dadosEmail, posicao: x};
      $.ajax({
          type: "POST",
          url: "/associados/mensagem/enviar/email",
          data: data,
          async: false,
          success: function(html) {
            if(html == 1){
              var progression = 100*x/dadosEmail.requests.length;
              $('#progressbar').attr('aria-valuenow', progression).css('width', progression+'%');
            }else{
              alert(html);
            }    
          }
      });
    }
    $('#progressbar').attr('aria-valuenow', 100).css('width', '100%');
    bootbox.alert("Mensagens enviadas com sucesso!");

  }
</script>  
<?php else: ?>
<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">Enviar mensagem</h3>
      </div>
      <div class="panel-body">
        <div class="form-group">
           <form class="form-inline" role="form" method="POST" action="#">
                      <div class="row">
                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formMensagem->get('empresa')->getLabel(); ?></label>
                            <?= $this->formElement($formMensagem->get('empresa')); ?>
                            <?= $this->formElementErrors($formMensagem->get('empresa'), array('class' => 'alert alert-danger')); ?>
                          </div>
                        </div>
                        <div class='col-sm-4'>
                          <div class="form-group">
                              <label for="disabledTextInput"><?= $formMensagem->get('categoria_associado')->getLabel(); ?></label>
                              <?= $this->formElement($formMensagem->get('categoria_associado')); ?>
                              <?= $this->formElementErrors($formMensagem->get('categoria_associado'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>

                        <div class='col-sm-4'>
                          <div class="form-group">
                              <label for="disabledTextInput"><?= $formMensagem->get('anuidade')->getLabel(); ?></label>
                              <?= $this->formElement($formMensagem->get('anuidade')); ?>
                              <?= $this->formElementErrors($formMensagem->get('anuidade'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>

                      </div>

                      <div class="row" style="margin-top: 20px;">
                        <div class='col-sm-4'>
                          <div class="form-group">
                              <label for="disabledTextInput"><?= $formMensagem->get('adimplente')->getLabel(); ?></label>
                              <?= $this->formElement($formMensagem->get('adimplente')); ?>
                              <?= $this->formElementErrors($formMensagem->get('adimplente'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                        
                        <div class='col-sm-4'>
                          <div class="form-group">
                              <label for="disabledTextInput"><?= $formMensagem->get('assunto')->getLabel(); ?></label>
                              <?= $this->formElement($formMensagem->get('assunto')); ?>
                              <?= $this->formElementErrors($formMensagem->get('assunto'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                      </div>

                      <div class="row" style="margin-top: 20px;">
                        <div class='col-sm-12'>
                          <label for="disabledTextInput"><?= $formMensagem->get('mensagem')->getLabel(); ?></label>
                          <?= $this->formElement($formMensagem->get('mensagem')); ?>
                          <?= $this->formElementErrors($formMensagem->get('mensagem'), array('class' => 'alert alert-danger')); ?>
                        </div>
                      </div>

                      <div class="row" style="margin-top:20px;">
                        <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                          <img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
                          Salvar
                        </button>
                      </div>
                </form>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- MENSAGENS DESTE EVENTO -->
    <?php if(!$mensagens || count($mensagens) == 0): ?>
      <div class="container theme-showcase" role="main">
        <div class="alert alert-info">Nenhuma mensagem enviada!</div>
      </div>

    <?php else: ?>

     <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Mensagens enviadas</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">Empresa</th>
                  <th style="text-align: center">Categoria</th>
                  <th style="text-align: center">Assunto</th>
                  <th style="text-align: center">Mensagem</th>
                  <th style="text-align: center">Data/hora de envio</th>
              </tr>
              <?php foreach ($mensagens as $mensagem): ?>
              <tr>
                <td style="text-align: center"><?= $mensagem['nome_fantasia']; ?></td>
                <td style="text-align: center"><?= $mensagem['nome_categoria']; ?></td>
                <td style="text-align: center"><?= $mensagem['assunto']; ?></td>
                <td style="text-align: center"><?= $mensagem['mensagem']; ?></td>
                <td style="text-align: center"><?= $this->converterData($mensagem['data_hora_envio']); ?></td>
              
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>

        <script type="text/javascript">
      $(document).ready(function() {
        CKEDITOR.replace('mensagem');
      });
    </script>

<?php endif; ?>
