<div class="container theme-showcase" role="main" style="">

</div>
<div class="container theme-showcase" role="main" style="">
	<div class="card card-container">
            <img id="profile-img" class="img-responsive center-block" src="<?php echo $this->basePath('img/logo.png'); ?>" />
            <p id="profile-name" class="profile-name-card"></p>
		<?php echo $this->partial('form/login', array('form'=> $form, 'route'=> '', 'reCaptchaValid' => $reCaptchaValid, 'credenciais' => $credenciais)) ?>
	</div>
</div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#login").mask("999.999.999-99");
      });
    </script>