 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('graficoAssociadosQuestao'); ?>'" style="float: right;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Questão">
    Gráfico de questão</button>

    <button type="button" disabled class="btn btn-info" onclick="location.href='<?= $this->url('graficoAssociadosQuestionario'); ?>'" style="float: right;margin-right: 10px;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Questionario">
    Gráfico de questionário</button>

    <button type="button" class="btn btn-warning" onclick="location.href='<?= $this->url('graficoAssociadosRespondido'); ?>'" style="float: right;margin-right: 10px;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Respondidos">
    Gráfico de respondidos</button>

  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-success">
          <div class="panel-heading">
              <h3 class="panel-title">Gráfico de questionário</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formQuestionario, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>



    

    <?php if($respostasQuestoes): ?>

      <div class="container theme-showcase" role="main">
        <div class="row">
      <?php foreach ($respostasQuestoes as $questao): ?>
          <div class='col-sm-6'>
            <canvas id="questao_<?= $questao['questao']['id'] ?>" style="height: 500px;"></canvas>
          </div>
      <?php endforeach; ?>
        </div>
      </div>



      <script>
        window.onload = function () {
        <?php foreach ($respostasQuestoes as $questao): ?>
            new Chart(document.getElementById("questao_<?= $questao['questao']['id'] ?>"), {
                type: 'doughnut',
                data: {
                  labels: [
                    <?php foreach ($questao['respostas'] as $avaliacao): ?>
                      "<?= $avaliacao['titulo'] ?>",
                    <?php endforeach; ?>
                  ],
                  datasets: [
                    {
                      label: "Quantidade de respostas",
                      backgroundColor: ["#df7970", "#6d78ad","#51cda0", "#007bff", "#6c757d", "#17a2b8", "#ffc107", "#dc3545", "#343a40"],
                      data: [
                        <?php foreach ($questao['respostas'] as $avaliacao): ?>
                          "<?= $avaliacao['quantidade'] ?>",
                        <?php endforeach; ?>
                      ]
                    }
                  ]
                },
                options: {
                legend: { display: true, position: 'bottom' },
                title: {
                  display: true,
                  text: '<?= $questao['questao']['enunciado'] ?>'
                },
                
                }
            });

        <?php endforeach; ?>
        }
        </script>
    <?php endif; ?>