 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <button type="button" class="btn btn-success" onclick="location.href='<?= $this->url('graficoAssociadosQuestao'); ?>'" style="float: right;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Questão">
    Gráfico de questão</button>

    <button type="button" class="btn btn-info" onclick="location.href='<?= $this->url('graficoAssociadosQuestionario'); ?>'" style="float: right;margin-right: 10px;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Questionario">
    Gráfico de questionário</button>

    <button type="button" class="btn btn-warning" disabled onclick="location.href='<?= $this->url('graficoAssociadosRespondido'); ?>'" style="float: right;margin-right: 10px;">
    <img src="<?php echo $this->basePath('img/graficoPizza.png') ?>" alt="Respondidos">
    Gráfico de respondidos</button>

  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Gráfico de questões</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formQuestionario, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>



    

<?php if($respondidas): ?>
  <div class="container theme-showcase" role="main">
    <div class="row">
        <canvas id="pizzaRespondidas" style="height: 500px;"></canvas>
    </div>
  </div>

<script>
  window.onload = function () {
    new Chart(document.getElementById("pizzaRespondidas"), {
        type: 'doughnut',
        data: {
          labels: [
            "Respondidas", "Em aberto"
          ],
          datasets: [
            {
              label: "",
              backgroundColor: ["#df7970", "#6d78ad"],
              data: [
                <?= $respondidas->quantidade ?>,
                <?= $emAberto->quantidade ?>
              ]
            }
          ]
        },
        options: {
        legend: { display: true, position: 'bottom' },
        title: {
          display: true,
          text: 'Avaliações respondidas/am aberto'
        },
        
        }
    });
  }
</script>
<?php endif; ?>