<div class="container theme-showcase">
    <div class="row text-center">
        <div class="col-md-3 col-sm-0">

        </div>
        <div class="col-md-6 col-sm-1">
            <div class="panel panel-default">
                <form class="" role="form" method="POST" action="#">   
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-xs-2">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('bandeira')->getLabel()?></label>
                                    <div class="input-group">
                                        <?= $this->formElement($formIpag->get('bandeira')); ?>
                                        <?= $this->formElementErrors($formIpag->get('bandeira'), array('class' => 'alert alert-danger')); ?> 
                                    </div>
                                </div>
                            </div>
                            <div class="col-xs-10">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('number')->getLabel()?></label>
                                    <div class="input-group">
                                        <?= $this->formElement($formIpag->get('number')); ?>
                                        <?= $this->formElementErrors($formIpag->get('number'), array('class' => 'alert alert-danger')); ?> 
                                        <span class="input-group-addon">
                                            <img src="<?php echo $this->basePath('img/cartao.png') ?>" alt="Cartão">
                                        </span> 
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-xs-2 col-md-2">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('parcelas')->getLabel()?></label> 
                                    <?= $this->formElement($formIpag->get('parcelas')); ?>
                                    <?= $this->formElementErrors($formIpag->get('parcelas'), array('class' => 'alert alert-danger')); ?> 
                                </div>
                            </div>

                            <div class="col-xs-5 col-md-5">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('expiry_date')->getLabel()?></label> 
                                    <?= $this->formElement($formIpag->get('expiry_date')); ?>
                                    <?= $this->formElementErrors($formIpag->get('expiry_date'), array('class' => 'alert alert-danger')); ?> 
                                </div>
                            </div>

                            <div class="col-xs-5 col-md-5 pull-right">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('cvv')->getLabel()?></label> 
                                    <?= $this->formElement($formIpag->get('cvv')); ?>
                                    <?= $this->formElementErrors($formIpag->get('cvv'), array('class' => 'alert alert-danger')); ?> 
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-xs-12">
                                <div class="form-group"> 
                                    <label><?=$formIpag->get('holder')->getLabel()?></label> 
                                    <?= $this->formElement($formIpag->get('holder')); ?>
                                    <?= $this->formElementErrors($formIpag->get('holder'), array('class' => 'alert alert-danger')); ?> 
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="panel-footer">
                        <div class="row">
                            <div class="col-xs-12"> 
                                <button type="submit" class="btn btn-success btn-lg btn-block">CONFIRMAR PAGAMENTO</button> 
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="col-md-3 col-sm-0">

        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
        $("#expiry_date").mask("99/9999");
        $("#number").mask("9999 9999 9999 9999");
        $("#cvv").mask("999");
    });
</script>