<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('home'); ?>">Home</a></li>
    <li><a href="<?= $this->url('eventoAlterar', array('id' => $evento['id'])); ?>">Evento</a></li>
    <li class="active">Cadastrar transmissão</li>
  </ol>
</div>

<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Cadastrar transmissão do evento : <?= $evento->nome ?></h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
              <?php echo $this->partial('form/generic', array('form'=> $formTransmissao, 'route'=> '')) ?>
        </div>
      </div>
    </div>
  </div>
</div>

    <!-- LISTAGEM DE TRANSMISSOES -->
    <?php if(!$transmissoes || $transmissoes->count() == 0): ?>
      <div class="container theme-showcase" role="main">
        <div class="row">
          <div class="alert alert-info">Nenhuma transmissão cadastrada!</div>
        </div>
      </div>
    <?php else: ?>

     <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Transmissões cadastradas</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">Descrição</th>
                  <th style="text-align: center">Sala</th>
                  <th style="text-align: center">Início</th>
                  <th style="text-align: center">Fim</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach ($transmissoes as $transmissao): ?>
              <tr>
                <td style="text-align: center"><?= $transmissao->descricao; ?></td>
                <td style="text-align: center"><?= $transmissao->sala ?></td>
                <td style="text-align: center"><?= $this->converterData($transmissao->inicio); ?></td>
                <td style="text-align: center"><?= $this->converterData($transmissao->fim); ?></td>
                <td style="text-align: center">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('cadastrarTransmissao', array('evento' => $evento->id, 'transmissao' => $transmissao->id)); ?>'" style="cursor: pointer;">
                    <span style="margin-right:4px;"></span> 
                  <img src="<?php echo $this->basePath('img/deletar.png') ?>" onclick="alerta('<?= $this->url('deletarTransmissao', array('evento' => $evento->id, 'transmissao' => $transmissao->id)); ?>', 'deletar');" title="Deletar">
                </td>
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#inicio").mask("99/99/9999 99:99");
        $("#fim").mask("99/99/9999 99:99");
      });
    </script>