<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('home'); ?>">Home</a></li>
    <li><a href="<?= $this->url('eventoAlterar', array('id' => $evento['id'])); ?>">Evento</a></li>
    <li class="active">Cadastrar vídeo</li>
  </ol>
</div>

<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">
          <h3 class="panel-title">Cadastrar vídeo do evento : <?= $evento->nome ?></h3>
        </div>
        <div class="panel-body">
            <div class="form-group">
              <?php echo $this->partial('form/generic', array('form'=> $formVideo, 'route'=> '')) ?>
        </div>
      </div>
    </div>
  </div>
</div>

    <!-- LISTAGEM DE VÍDEOS -->
    <?php if(!$videos || $videos->count() == 0): ?>
      <div class="container theme-showcase" role="main">
        <div class="row">
          <div class="alert alert-info">Nenhum vídeo cadastrado!</div>
        </div>
      </div>
    <?php else: ?>

     <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Vídeos cadastrados</h3>
            </div>
            <div class="panel-body">
              <table class="table">
                <tr>
                  <th style="text-align: center">id</th>
                  <th style="text-align: center">Descrição</th>
                  <th style="text-align: center">Link</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach ($videos as $video): ?>
              <tr>
              <td style="text-align: center"><?= $video->id; ?></td>  
              <td style="text-align: center"><?= $video->descricao; ?></td>
                <td style="text-align: center"><a href="<?= $video->link_video ?>" target="_blank">Vídeo</a</td>
                <td style="text-align: center">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                    onclick="location.href='<?= $this->url('cadastrarVideo', array('evento' => $evento->id, 'video' => $video->id)); ?>'" style="cursor: pointer;">
                    <span style="margin-right:4px;"></span> 
                  <img src="<?php echo $this->basePath('img/deletar.png') ?>" onclick="alerta('<?= $this->url('deletarVideo', array('evento' => $evento->id, 'video' => $video->id)); ?>', 'deletar');" title="Deletar">
                </td>
              </tr>
            <?php endforeach; ?>
            </table>
            </div>
          </div>
        </div>
      </div>
    <?php endif; ?>