    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('eventoNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Eventos</li>
      </ol>
    </div>
    <!-- LISTAGEM DOS EVENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de eventos</h3>
            </div>
            <div class="panel-body">
              <?php if($eventos->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Sigla</th>
                  <th style="text-align: center">Nome</th>
                  <th style="text-align: center">Período</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($eventos as $evento): ?>
              <tr>
                <td style="text-align: center"><?= $evento['sigla']; ?></td>
                <td style="text-align: center"><?= $evento['nome']; ?></td>
                <td style="text-align: center"><?= $this->converterData($evento['data_inicio']).' a '.$this->converterData($evento['data_fim']); ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                  onclick="location.href='<?= $this->url('eventoAlterar', array('id' => $evento['id'])); ?>'" style="cursor: pointer;">
                  <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/check.png'); ?>" title="Campos obrigatórios" onclick="location.href='<?= $this->url('camposObrigatorios', array('id' => $evento['id'])); ?>'" style="cursor: pointer;">
                    <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/msg.png'); ?>" title="Mensagem" onclick="location.href='<?= $this->url('mensagemParticipante', array('id' => $evento['id'])); ?>'" style="cursor: pointer;">
                    <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/inscricao.png'); ?>" title="Nova inscrição" onclick="location.href='<?= $this->url('realizarInscricao', array('siglaEvento' => $evento['sigla'])); ?>'" style="cursor: pointer;">

                    <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/excel.png'); ?>" title="Importar pagamentos da cielo" onclick="location.href='<?= $this->url('planilhaCielo'); ?>'" style="cursor: pointer;">

                    <span style="margin-right:4px;"></span>  
                    <img src="<?= $this->basePath('img/exportar_excel.png'); ?>" title="Exportar inscrições" onclick="location.href='<?= $this->url('relatorioInscricoes', array('evento' => $evento['id'])); ?>'" style="cursor: pointer;">

                    
                    <span style="margin-right:4px;"></span>  
                    <a href="<?= $this->url('buscarCheckin', array('siglaEvento' => $evento['sigla'])); ?>" target="_blank">
                      <img src="<?= $this->basePath('img/assigntome.png'); ?>" title="Checkin" style="cursor: pointer;">
                    </a>

                    <span style="margin-right:4px;"></span>  
                    <a href="<?= $this->url('buscarCertificado', array('siglaEvento' => $evento['sigla'], 'numeroCertificado' => 1)); ?>" target="_blank">
                      <img src="<?= $this->basePath('img/certificado.png'); ?>" title="Certificados" style="cursor: pointer;">
                    </a>

                    <span style="margin-right:4px;"></span>  
                    <a href="<?= $this->url('listarTrabalhosPublic', array('page' => 1, 'sigla' => $evento['sigla'])); ?>" target="_blank">
                      <img src="<?= $this->basePath('img/trabalho.png'); ?>" title="Trabalhos" style="cursor: pointer;">
                    </a>
                  
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhum evento encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($eventos,
                                        'Sliding',
                                        'view/paginator', array('route' => 'evento')); 
          ?>
        </div>
      </div>
    <script type="text/javascript">
      $(document).ready(function() {
        //formEmpresa();
      });
    </script>