 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('eventoNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('evento'); ?>">Eventos</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir evento</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/evento', array('form'=> $formEvento, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>
    <script type="text/javascript">
      $(document).ready(function() {
        formEvento();
         CKEDITOR.replace("observacoes");

        CKEDITOR.replace('mensagem_cadastro_novo');
        CKEDITOR.replace('mensagem_cadastro_antigo');
        CKEDITOR.replace('mensagem_pagamento');
        CKEDITOR.replace('mensagem_transferencia');
      CKEDITOR.replace('mensagem_trabalho');
      });
    </script>