 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('empresaNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>
<ol class="breadcrumb" style="margin-bottom: 0px;">
  <li><a href="<?= $this->url('home'); ?>">Home</a></li>
  <li><a href="<?= $this->url('empresa'); ?>">Empresas</a></li>
  <li class="active">Alterar</li>
</ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar empresa</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/empresa', array('form'=> $formEmpresa, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-success">
          <div class="panel-heading">
              <h3 class="panel-title">Configurar paypal</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formPaypal, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Configurar cielo</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formCielo, 'route'=> '')) ?>
            </div>
          </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
	    $(document).ready(function() {
			  formEmpresa();
        CKEDITOR.replace("dados_deposito");
		  });
    </script>