<?php if(!$this->params)$this->params = array();?>
<?php $form->prepare(); ?>

<?php if($this->route || $this->route):?>
    <?php $form->setAttribute('action', $this->url($this->route, $this->params)); ?>
<?php else: ?>
	<?php $form->setAttribute('action', "#"); ?>
<?php endif;?>

<?= $this->form()->openTag($form); ?>
<?php $row = 0; ?>
<div class="row" style="margin-top:20px;">
<?php foreach ($form->getElements() as $element): ?>
		<?php if(in_array($element->getName(), array(
				'observacoes', 
				'mensagem_cadastro_novo', 
				'mensagem_cadastro_antigo', 
				'mensagem_pagamento', 
				'mensagem_transferencia', 
				'mensagem_trabalho'
			))): 
		?>
			</row>

			<div class="row" style="margin-top:70px;">
				<div class='col-sm-12'>
						<label for="<?=$element->getName()?>" ><?=$element->getLabel()?></label>
					<div class="text-center" id="group-<?= $element->getName(); ?>" style="padding: 10px;">
						<?= $this->formElement($element); ?>
			        	<?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
			        </div>
				</div>
			</div>
		<?php else: ?>
			<?php 
				$attributes = $element->getAttributes();
				if(isset($attributes['type']) && $attributes['type'] == 'hidden'){
					echo $this->formElement($element);
					continue;
				}
				$row++; 
				if($row == 4): 
					$row = 1;
			?>
			</div>
			<div class="row" style="margin-top:20px;">
			<?php endif; ?>
				
				<?php 
					if (in_array($element->getName(), array('forma_paypal', 'forma_transferencia', 'forma_ipag'))) {
						$row--;
						continue;
					}	
				?>

				<?php if($element->getName() == 'forma_cielo'): ?>
					<div class='col-sm-4' style="margin-bottom: 20px;">
						<div class="form-group" id="group-aparecer">
							<label for="aparecer">Formas de pagamento:</label><br>
							<label for="aparecer" style="width:139px;"><?=$form->get('forma_cielo')->getLabel()?></label>
							<?= $this->formElement($form->get('forma_cielo')); ?>
							<?= $this->formElementErrors($form->get('forma_cielo'), array('class' => 'alert alert-danger')); ?>
							<br>
							<label for="aparecer" style="width:139px;"><?=$form->get('forma_paypal')->getLabel()?></label>
							<?= $this->formElement($form->get('forma_paypal')); ?>
							<?= $this->formElementErrors($form->get('forma_paypal'), array('class' => 'alert alert-danger')); ?>
							<br>
							<label for="aparecer" style="width:139px;"><?=$form->get('forma_transferencia')->getLabel()?></label>
							<?= $this->formElement($form->get('forma_transferencia')); ?>
							<?= $this->formElementErrors($form->get('forma_transferencia'), array('class' => 'alert alert-danger')); ?>
							<br>
							<label for="aparecer" style="width:139px;"><?=$form->get('forma_ipag')->getLabel()?></label>
							<?= $this->formElement($form->get('forma_ipag')); ?>
							<?= $this->formElementErrors($form->get('forma_ipag'), array('class' => 'alert alert-danger')); ?>
						</div>
					</div>
				<?php continue; ?>
				<?php endif; ?>

		        <div class='col-sm-4'>
	                <div class="form-group" id="group-<?= $element->getName(); ?>">
		        <?php if($element->getLabel()) :?>
		        
		        <label for="<?=$element->getName()?>" style="width:139px;"><?=$element->getLabel()?></label>
		        
		        <?php endif;?>
		        	
		        	<?= $this->formElement($element); ?>
		        	<?= $this->formElementErrors($element, array('class' => 'alert alert-danger')); ?>
		     		</div>
	            </div>
				
					


		<?php endif; ?>

<?php endforeach; ?>
</div>
<div class="row" style="margin-top:20px;">
	<?php 
		if(isset($this->botao)): 
			echo $this->botao;
		else:
	?>
	<button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
		<img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
		Salvar
	</button>
<?php endif; ?>
</div>


<?= $this->form()->closeTag($form); ?>