
<div class="panel panel-default">    
	<div class="panel-body">
		<div class="form-group">
			<form name="formValores" action="#" method="POST">
				<!-- GERAR RADIO DE PAGAMENTO -->
				<?php foreach ($valores as $valor) : ?>
					<div class="panel panel-default">
			          	<div class="panel-heading">
			              <h3 class="panel-title">
			              	<input type="radio" value="<?= $valor['id']; ?>" required="required" name="valor_inscricao" aria-invalid="false">
			              	<?= $valor['nome_categoria'] ?> 
			              	<span>- <?= html_entity_decode($valor['descricao_categoria']) ?></span>
			              	<br>
			              	<?= $this->exibirMonetario($valor['valor_inscricao']) ?> até <?= $this->converterData($valor['data_fim_valor']); ?>
			                  

			              </h3>
			           	</div>
			        </div>
				<?php endforeach; ?>


			  <div class="row text-center" style="margin-top:20px;">
			  	<button type="submit" class="btn btn-warning" style="width: 95%;">
			  		<img src="<?= $this->basePath('img/ticket.png'); ?>" alt="Participar">
			  		Quero participar
			  	</button>
			  </div>
			</form>
		</div>
	</div>
</div>
