
<div class="panel panel-default">    
	<div class="panel-body">
		<div class="form-group">
			<form name="formValores" action="#" method="POST">
				<!-- GERAR RADIO DE PAGAMENTO -->
				<?php foreach ($valores as $valor) : ?>
					<div class="panel panel-default">
			          	<div class="panel-heading">
			              <h3 class="panel-title">
							<div>
								<input type="radio" value="<?= $valor['id']; ?>" required="required" name="valor_inscricao" aria-invalid="false">
			              		<?= $valor['nome_categoria'] ?>
							</div>
			              	<div style="font-size: 14;font-weight: 600;margin-top:10px;line-height:1.4;">
								<?= html_entity_decode($valor['descricao_categoria']) ?>
							</div>
			              	<div style="font-size: 16;font-weight: 600;margin-top:10px;">
								<?= $this->exibirMonetario($valor['valor_inscricao']) ?> até <?= $this->converterData($valor['data_fim_valor']); ?>
							</div>
			                  

			              </h3>
			           	</div>
			        </div>
				<?php endforeach; ?>


			  <div class="row text-center" style="margin-top:20px;">
			  	<button type="submit" class="btn btn-warning" style="width: 95%;">
			  		<img src="<?= $this->basePath('img/ticket.png'); ?>" alt="Participar">
			  		Quero participar
			  	</button>
			  </div>
			</form>
		</div>
	</div>
</div>
