 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('avaliadorNovo'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo avaliador</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('avaliadoresCompeticao'); ?>">Lista de avaliadores</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title">Cadastro de avaliador</h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <?php echo $this->partial('form/generic', array('form'=> $formAvaliador, 'route'=> '', 'btnClass' => 'btn btn-primary')) ?>
              </div>
            </div>
      </div>
    </div>
    </div>

    <script type="text/javascript">
      $(document).ready(function() {
        $("#cpf").mask("999.999.999-99");
      });
    </script>