 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('faculdadeNovo'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova faculdade</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('faculdades'); ?>">Lista de faculdades</a></li>
      <li class="active">Alterar</li>
    </ol>
  </div>


  <!-- ABAS DE NAVEGAÇÃO -->
  <div class="container theme-showcase" role="main">
  <div class="row">

    <ul class="nav nav-tabs">
      <li class="active">
        <a style="background-color:#428bca;margin-right: 0px;color: #FFFFFF;">
          <img src="<?= $this->basePath('img/faculdade.png') ?>"> Faculdade
        </a>
      </li>
      <li>
        <a style="background-color:#fcf8e3;margin-right: 0px;" href="<?= $this->url('faculdadeOradores', array('idFaculdade' => $faculdade->id)); ?>">
          <img src="<?= $this->basePath('img/orador.png') ?>"> Oradores
        </a>
      </li>
    </ul>
    

  </div>
</div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title">Alterar faculdade</h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <?php echo $this->partial('form/generic', array('form'=> $formFaculdade, 'route'=> '', 'btnClass' => 'btn btn-primary')) ?>
              </div>
            </div>
      </div>
    </div>
    </div>