 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('faculdades'); ?>">Lista de faculdades</a></li>
      <li class="active">Importar</li>
    </ol>
  </div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-primary">
          <div class="panel-heading">
              <h3 class="panel-title">Importar faculdades e oradores</h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <?php echo $this->partial('form/generic', array('form'=> $formUpload, 'route'=> '', 'btnClass' => 'btn btn-primary')) ?>
              </div>
            </div>
      </div>
    </div>
    </div>