  <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('faculdadeNovo'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova faculdade</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('faculdades'); ?>">Lista de faculdades</a></li>
      <li class="active">Oradores</li>
    </ol>
  </div>


  <!-- ABAS DE NAVEGAÇÃO -->
  <div class="container theme-showcase" role="main">
  <div class="row">

    <ul class="nav nav-tabs">
      <li>
        <a style="background-color:#428bca;margin-right: 0px;color: #FFFFFF;" href="<?= $this->url('faculdadeAlterar', array('id' => $faculdade->id)); ?>">
          <img src="<?= $this->basePath('img/faculdade.png') ?>"> Faculdade
        </a>
      </li>
      <li class="active">
        <a style="background-color:#fcf8e3;margin-right: 0px;">
          <img src="<?= $this->basePath('img/orador.png') ?>"> Oradores
        </a>
      </li>
    </ul>
    

  </div>
</div>


    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-warning">
          <div class="panel-heading">
              <h3 class="panel-title">Cadastro de orador - <?= $faculdade['nome'] ?></h3>
            </div>
            <div class="panel-body">
              <div class="form-group">
                <?php echo $this->partial('form/generic', array('form'=> $formOrador, 'route'=> '', 'btnClass' => 'btn btn-warning')) ?>
              </div>
          </div>
      </div>
    </div>
    </div>

    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('faculdadeOradores', array('idFaculdade' => $faculdade->id)); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo orador</button>
    </div>

    <!-- ORADORES -->
    <div class="container theme-showcase" role="main" style="margin-bottom:10px;">
      <div class="row">
          <div class="panel panel-warning">
            <div class="panel-heading">
              <h3 class="panel-title">Lista de oradores - <?= $faculdade['nome'] ?></h3>
            </div>
            <div class="panel-body">
              <?php if(count($oradores) > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Nome</th>
                  <th style="text-align: center">Email</th>
                  <th style="text-align: center">Status</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($oradores as $orador): ?>
              <tr>
                <td style="text-align: center"><?= $orador['nome']; ?></td>
                <td style="text-align: center"><?= $this->caracterVazio($orador['email']); ?></td>
                <td style="text-align: center"><?= $this->status($orador['ativo']); ?></td>
                <td style="text-align: center;">
                  <img onclick="location.href='<?= $this->url('faculdadeOradores', array('idFaculdade' => $faculdade->id, 'id' => $orador['id'])); ?>'" src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" style="cursor: pointer;">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhum orador encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>