<div class='col-sm-4'>
	<div class="form-group">
		<label for="disabledTextInput"><?=$orador1->getLabel()?></label>
		<?= $this->formElement($orador1); ?>
		<?= $this->formElementErrors($orador1, array('class' => 'alert alert-danger')); ?>
	</div>
</div>

<div class='col-sm-4'>
	<div class="form-group">
		 <label for="disabledTextInput"><?=$orador2->getLabel()?></label>
		 <?= $this->formElement($orador2); ?>
		 <?= $this->formElementErrors($orador2, array('class' => 'alert alert-danger')); ?>
	</div>
</div>