  <div class="container theme-showcase" role="main" style="margin-bottom:40px;padding:0px;">
    <div class="breadcrumb2 flat">
      <a href="<?= $evento->site_evento; ?>">Web site do evento</a>
      <a href="#">Inscrição</a>
      <a href="#" class="active">Atividades</a>
      <a href="#">Pagamento</a>
    </div>
  </div>

  <div class="container theme-showcase" role="main" style="margin-top:100px;">
      <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

      <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>
      
      <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>
  </div>

  <!-- GERAR OPÇÕES -->
<?php if(!$opcoes || $opcoes->count() == 0): ?>
    <div class="container theme-showcase" role="main">
      <div class="alert alert-info">Nenhuma opção de programação!</div>
    </div>
    <div class="container theme-showcase" role="main">
      <!-- BOTÃO, IR PARA PAGAMENTO -->
      <div style="margin-top:20px;" class="row">
        <button style="float: right;margin-right: 10px;" onclick="location.href='<?= $this->url('pagamento'); ?>'" class="btn btn-success" type="button">
          <img alt="Próximo" src="<?php echo $this->basePath('img/salvar.png'); ?>">
          Próximo
        </button>
      </div>
    </div>
    <?php else: ?>
  <?php 
    $idOpcao = 0;
  ?>
  <form class="form-inline" method="POST" action="#" name="formAtividade">
  <?php $contadorOpcoes = 0; ?>
  <?php foreach ($opcoes as $opcao): ?>
      <?php if($opcao->evento_opcao != $idOpcao){
        //ESCREVER CABECALHO
          $contadorOpcoes++;
          if($idOpcao != 0){
            $htmlOpcao .= '</div>
                        </table>
                        </div>
                      </div>
                    </div>
                  </div>';
            echo $htmlOpcao;
          }

          $htmlOpcao = '
            <div class="container theme-showcase" role="main">
              <div class="row">
                  <div class="panel panel-success">
                    <div class="panel-heading">
                      <h3 class="panel-title">'.$opcao->titulo.' - '.$this->converterData($opcao->data).'</h3>
                    </div>
                    <div class="panel-body">
                      <table class="table">
                        <tr>
                          <th style="text-align: center">Selecionar</th>
                          <th style="text-align: center">Atividade</th>
                          <th style="text-align: center">Local</th>
                          <th style="text-align: center">Descrição</th>
                      </tr>

                      <div class="form-group">
             ';
          $idOpcao = $opcao->evento_opcao; 
        }
        ?>
      <?php 
        //CORPO
        $htmlOpcao .= '
                    <tr>
                      <td style="text-align: center"><input type="radio" required="required" name="atividade'.$contadorOpcoes.'" value="'.$opcao->id.'"></td>
                      <td style="text-align: left; font-size:15px;">'.$opcao->atividade.'</td>
                      <td style="text-align: left; font-size:15px;">'.$opcao->local.'</td>
                      <td style="text-align: left; font-size:15px;">'.$this->caracterVazio(html_entity_decode($opcao->descricao)).'</td>
                    </tr>';
      ?>         
    <?php endforeach; ?>
    <?php 
        $htmlOpcao .= '</div>
                        </table>
                        </div>
                      </div>
                    </div>
                  </div>';
            echo $htmlOpcao;
    ?>
    <div class="container theme-showcase" role="main">
      <div style="margin-top:20px;" class="row">
        <button style="float: right;margin-right: 10px;" class="btn btn-success" type="submit">
          <img alt="Salvar" src="<?php echo $this->basePath('img/salvar.png'); ?>">
          Salvar
        </button>
      </div>
    </div>
    </form>
    <?php endif; ?>