<style type="text/css">
  .soldicon {position:absolute;
    z-index:2;
    top:73%; 
    left:91%;
    width:177px; 
    height:138px;
    background:url(/img/ganhador.png) no-repeat top left;
}

.apelante{
  background-color: #f8d7da;
}

.apelado{
 background-color: #dff0d8; 
}

</style>

<div class="container theme-showcase" role="main" style="margin-bottom:10px;">
  <div class="jumbotron">
    <h1><?= $competicao->nome ?></h1>
    <p><?= html_entity_decode($competicao->descricao) ?></p>
  

    <div class="card shadow mb-4">
      <div class="card-header py-3">
        <div class="row">
          <div class="col-sm-12">
            <h5 class="m-0 font-weight-bold text-primary">Classificação - <?= $competicao->nome ?></h6>
          </div>
        </div>
      </div>
      <div class="card-body">
        <div class="row">
          <div class="col-sm-12">
            <?php if($faculdades->count() > 0): ?>
            <table class="table">
              <tr>
                <th style="text-align: center">Posição</th>
                <th style="text-align: center">Faculdade</th>
                <th style="text-align: center">Pontuação</th>
            </tr>
            <?php foreach($faculdades as $key => $faculdade): ?>
            <tr>
              <td style="text-align: center"><?= $key+1; ?></td>
              <td style="text-align: center"><?= $faculdade['nome_faculdade']; ?></td>
              <td style="text-align: center"><?= $faculdade['nota']; ?> pontos</td>
            </tr>
            <?php endforeach; ?>
          </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhuma faculdade encontrada!</div>
          <?php endif; ?>
          </div>
        </div>
     
      </div>
    </div>
  </div>
</div>
