 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
      <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('competicaoNovo'); ?>'" style="float: right;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Nova competição</button>

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('competicoes'); ?>">Lista de competições</a></li>
      <li class="active">Novo</li>
    </ol>
  </div>


  <!-- ABAS DE NAVEGAÇÃO -->
  <div class="container theme-showcase" role="main">
  <div class="row">

    <ul class="nav nav-tabs">
      <li>
        <a style="background-color:#428bca;margin-right: 0px;color: #FFFFFF;" href="<?= $this->url('competicaoAlterar', array('idCompeticao' => $competicao->id)); ?>">
          <img src="<?= $this->basePath('img/competicao.png') ?>"> Competição
        </a>
      </li>
      <li>
        <a class="active" style="background-color:#dff0d8;margin-right: 0px;">
          <img src="<?= $this->basePath('img/sala.png') ?>"> Salas
        </a>
      </li>

      <li>
        <a style="background-color:#fcf8e3;margin-right: 0px;" href="<?= $this->url('competicaoChaveamento', array('idCompeticao' => $competicao->id)); ?>">
          <img src="<?= $this->basePath('img/chaveamento.png') ?>"> Chaveamento
        </a>
      </li>
    </ul>
    

  </div>
</div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-success">
          <div class="panel-heading">
              <h3 class="panel-title">Cadastro de salas - <?= $competicao->nome ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formSala, 'route'=> '', 'btnClass' => 'btn btn-success')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>



    <!-- Lista das salas -->
    <div class="container theme-showcase" role="main" style="margin-bottom:10px;">
      <div class="row">
          <div class="panel panel-success">
            <div class="panel-heading">
              <h3 class="panel-title">Lista de salas</h3>
            </div>
            <div class="panel-body">
              <?php if(count($salas) > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Nome</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($salas as $sala): ?>
              <tr>
                <td style="text-align: center"><?= $sala['nome']; ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                  onclick="location.href='<?= $this->url('competicaoSalas', array('idCompeticao' => $competicao->id, 'idSala' => $sala['id'])); ?>'" style="cursor: pointer;">

                  <span style="margin-right:4px;"></span>

                  <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('competicaoDeletarSalas', array('idCompeticao' => $competicao->id, 'idSala' => $sala['id'])) ?>', 'deletar');">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhuma sala encontrada!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>