<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        
        <?php echo $this->headTitle($this->translate('Time sistemas'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css'); ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            //->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/ckEditor/ckeditor.js')
            ->prependFile($this->basePath() . '/js/funcoes.js')
            ->prependFile($this->basePath() . '/js/jquery.maskedinput.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
        ; ?>

    </head>
    <body role="document">
        <div class="container theme-showcase" role="main" style="margin-top:100px;">
            <div class="row">
                <?= $this->flashMessenger()->render('error', array('alert', 'alert-danger')) ?>   

                <?= $this->flashMessenger()->render('warning', array('alert',  'alert-warning')) ?>
                
                <?= $this->flashMessenger()->render('success', array('alert',  'alert-success')) ?>
            </div>
        </div>

        <?php echo $this->content; ?>
    </body>
</html>