 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('buscarCheckin', array('siglaEvento' => $siglaEvento)); ?>">Buscar outro inscrito</a></li>
      <li class="active">Confirmar presença</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Confirmar presença</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formPessoa, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>
  <script type="text/javascript">
    $(document).ready(function() {
      $.mask.definitions['~'] = "[+-]";
      $("#cpf").mask("999.999.999-99");
      $("#cpf").focus();
    });
  </script>