 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">

    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('categoriaCliente'); ?>">Categoria de clientes</a></li>
      <li class="active">Upload sócios</li>
    </ol>
  </div>
  <?php if($numeroSocios > 0): ?>
    <div class="container theme-showcase" role="main">
      <div class="alert alert-info">
        <strong><?= $numeroSocios ?></strong> sócios processados.
      </div>
    </div>
  <?php endif; ?>
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Upload de sócios para validação</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formUpload, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>