    <div class="container theme-showcase" role="main" style="">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                  <form class="form-inline" role="form" method="POST" action="#">
                      <div class="row">
                        <div class='col-sm-3'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('nome')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('nome')); ?>
                          </div>
                        </div>

                        <div class='col-sm-3'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('empresa')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('empresa')); ?>
                          </div>
                        </div>

                        <div class='col-sm-3'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('questionario')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('questionario')); ?>
                          </div>
                        </div>

                        <div class='col-sm-3'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('respondida')->getLabel(); ?></label>
                            <?= $this->formElement($formPesquisa->get('respondida')); ?>
                          </div>
                        </div>
                      </div>

                      <div class="row" style="margin-top:20px;">
                        <button type="submit" name="pesquisar" class="btn btn-success" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath('img/pesquisar.png'); ?>" alt="Pesquisar"> Pesquisar</button>
                        <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath('img/limpar.png'); ?>"> Limpar</button>
                      </div>
                </form>
            </div>
          </div>
        </div>
      </div>
    </div>



    <!-- LISTAGEM DOS EQUIPAMENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Lista de respostas</h3>
            </div>
            <div class="panel-body">
              <?php if(!isset($params['questionario']) || empty($params['questionario'])): ?>
              <div class="alert alert-warning">Favor selecionar um questionário!</div>
              <?php else: ?>
              <?php if($questionarios->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Associado</th>
                  <th style="text-align: center">Questionario</th>
                  <th style="text-align: center">Data/hora da resposta</th>
                  <th style="text-align: center">Visualizar</th>
              </tr>
              <?php foreach($questionarios as $questionario): ?>
              <tr>
                <td style="text-align: center"><?= $questionario['nome_completo']; ?></td>
                <td style="text-align: center"><?= $questionario['nome_questionario']; ?></td>
                <td style="text-align: center"><?= $this->converterData($questionario['data_hora_resposta']); ?></td>
                <td style="text-align: center;">
                  <?php if(!empty($questionario['id_resposta'])): ?>
                    <img onclick="visualizarQuestionario('<?= $this->url('visualizarQuestionarioCliente', array('id' => $questionario['id_resposta'])) ?>');" src="<?= $this->basePath('img/visualizar.png'); ?>" title="Editar"  style="cursor: pointer;">
                  <?php endif; ?>
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhum questionário encontrado!</div>
        <?php endif; ?>
          <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($questionarios,
                                        'Sliding',
                                        'view/paginator', array('route' => 'empresa')); 
          ?>
        </div>
      </div>

       <script type="text/javascript">
          function visualizarQuestionario(url){
            $.colorbox({href:url});
          }

      </script>