    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-danger">
          <div class="panel-heading">
              <h3 class="panel-title">Cadastro de questão</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <form name="frmQuestao" method="POST" action="<?= $this->url('questionarioQuestaoAssociado', array('idQuestionario' => $idQuestionario, 'idQuestao' => $idQuestao)); ?>">
                  <div class="row">
                    <div class='col-sm-2'>
                        <div class="form-group" id="group-<?= $formQuestao->get('ordem')->getName(); ?>">
                            <label for="<?=$formQuestao->get('ordem')->getName()?>"><?=$formQuestao->get('ordem')->getLabel()?></label>  
                            <?= $this->formElement($formQuestao->get('ordem')); ?>
                            <?= $this->formElementErrors($formQuestao->get('ordem'), array('class' => 'alert alert-danger')); ?>
                        </div>
                    </div>

                  </div>

                  <div class="row" style="margin-top:20px;">
                    <div class='col-sm-12'>
                      <label for="<?=$formQuestao->get('enunciado')->getName()?>"><?=$formQuestao->get('enunciado')->getLabel()?></label>  
                      <?= $this->formElement($formQuestao->get('enunciado')); ?>
                      <?= $this->formElementErrors($formQuestao->get('enunciado'), array('class' => 'alert alert-danger')); ?>
                    </div>
                  </div>

                  <div class="row" style="margin-top:20px;">
                    <button type="submit" class="btn btn-success" style="float: right;margin-right: 10px;">
                      <img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
                      Salvar
                    </button>
                  </div>
                  </form>
            </div>
          </div>
      </div>
    </div>
    </div>

        <script type="text/javascript">
      $(document).ready(function() {
        //CKEDITOR.replace('enunciado');
      });
    </script>