    <div class="container theme-showcase" role="main" style="width: 100%">
      <div class="row">
          <div class="panel panel-danger">
          <div class="panel-heading">
              <h3 class="panel-title"><?= $primeiraQuestao['nome'] ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <div class="row">
                    <div class="col-sm-12">
                      <?= html_entity_decode($primeiraQuestao['descricao']); ?>
                    </div>
                  </div>
                  <hr>
                  <?php echo $this->partial('responder/questionario', array('questionario'=> $questionario, 'route'=> '', 'idQuestao' => $primeiraQuestao['id'], 'form' => $formQuestionario, 'idQuestionario' => $idQuestionario)) ?>
            </div>
          </div>
      </div>
    </div>
    </div>
    
        <script type="text/javascript">
      $(document).ready(function() {
        //CKEDITOR.replace('enunciado');
      });
    </script>