<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-md-3">
      <?php echo $this->partial(
        'menu/cliente',
        array(
          'associado' => $associado,
          'questionario' => $questionario,
          'pagina' => 'educacao-continuada'
        )
      );
      ?>
    </div>
    
    <div class="col-md-9">
      <div class="row">
        <?php foreach ($continuadas as $continuada) : ?>
            <div class="col-sm-6 col-md-6">
                <a href="<?= strtolower($continuada['link_vimeo']) ?>" target="_blank">
                  <div class="thumbnail  text-center">
                      <div class="caption">
                          <h2 style="font-weight: 900;"><?= $continuada['nome'] ?></h2>
                          <p style="font-weight: 700;font-size: 17px;"><?= html_entity_decode($continuada['descricao']) ?></p>
                          <p>PALESTRANTES</p>

                      </div>
                      <img style="width: 242px;height: 200px;" src="<?php echo $this->basePath($continuada['imagem']) ?>" alt="Educação continuada">
                      <p style="margin-top: 10px;font-weight: 700;"><?= $continuada['palestrantes'] ?></p>
                      <div class="caption">
                          <h3>Moderador</h3>
                          <p><?= $continuada['moderador'] ?></p>
                      </div>
                  </div>
                </a>
            </div>

        <?php endforeach; ?>
        


      </div>
      <div style="float:right;">
        <?php echo $this->paginationControl(
          $continuadas,
          'Sliding',
          'view/paginator',
          array('route' => 'educacaoContinuada')
        );
        ?>
      </div>
    </div>

  </div>
</div>
