 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('home'); ?>">Home</a></li>
      <li><a href="<?= $this->url('visualizaInscricoes'); ?>">Gerenciar inscrições</a></li>
      <li>
        <a href="<?= $this->url('gerenciarInscricao', array('id' => $inscricao->id)); ?>">Visualizar inscrição <?= $inscricao->id; ?></a>
      </li>
      <li class="active">Alterar cliente</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Alteração de cliente</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formPessoa, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>
