 <div class="row">
          <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">

                	<!-- form de pesquisa -->
                  <form class="form-inline" role="form" method="POST" action="#">
                      <div class="row">
                        
                        <div class='col-sm-4'>
                          <div class="form-group">
                             <label for="disabledTextInput"><?=$formPesquisa->get('cliente')->getLabel()?></label>
                             <?= $this->formElement($formPesquisa->get('cliente')); ?>
                          </div>
                        </div>

                        <div class='col-sm-4'>
                        <div class="form-group">
                          <label for="disabledTextInput"><?= $formPesquisa->get('unidade')->getLabel(); ?></label>
                          <?= $this->formElement($formPesquisa->get('unidade')); ?>
                        </div>
                      </div>

                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('etiqueta')->getLabel() ?></label>
                            <?=  $this->formElement($formPesquisa->get('etiqueta')); ?>
                          </div>
                        </div>
                    </div>



                      <div class="row" style="margin-top:20px;">
                        
                        <div class='col-sm-4'>
                          <div class="form-group">
                             <label for="disabledTextInput"><?=$formPesquisa->get('nome_rede')->getLabel()?></label>
                             <?= $this->formElement($formPesquisa->get('nome_rede')); ?>
                          </div>
                        </div>

                        <div class='col-sm-4'>
                        <div class="form-group">
                          <label for="disabledTextInput"><?= $formPesquisa->get('prioridade_atendimento')->getLabel(); ?></label>
                          <?= $this->formElement($formPesquisa->get('prioridade_atendimento')); ?>
                        </div>
                      </div>

                        <div class='col-sm-4'>
                          <div class="form-group">
                            <label for="disabledTextInput"><?= $formPesquisa->get('ativo')->getLabel() ?></label>
                            <?=  $this->formElement($formPesquisa->get('ativo')); ?>
                          </div>
                        </div>
                      </div>

                      <div class="row" style="margin-top:20px;">
                        <button type="submit" name="limpar" class="btn btn-default" style="float: right;margin-right: 20px;">
                        <img src="<?= $this->basePath("img/limpar.png"); ?>"> Limpar</button>
                        <button type="submit" name="enviar" class="btn btn-success" style="float: right;margin-right: 10px;">
                        <img src="<?= $this->basePath("img/pesquisar.png"); ?>"> Pesquisar</button>
                      </div>

                </form>


            	</div>
          </div>
      </div>
    </div>
    </div>
    <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
       <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('equipamentoNovo'); ?>'" style="float: right;width:100px;">
      <img src="<?php echo $this->basePath('img/novo.png') ?>" alt="Novo">
      Novo</button>

      <ol class="breadcrumb" style="margin-bottom: 0px;">
        <li><a href="<?= $this->url('home'); ?>">Home</a></li>
        <li class="active">Equipamentos</li>
      </ol>
    </div>
    <!-- LISTAGEM DOS EQUIPAMENTOS -->
    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Listagem de equipamentos</h3>
            </div>
            <div class="panel-body">
              <?php if($equipamentos->count() > 0): ?>
              <table class="table">
                <tr>
                  <th style="text-align: center">Cliente</th>
                  <th style="text-align: center">Etiqueta</th>
                  <th style="text-align: center">Nome na rede</th>
                  <th style="text-align: center">Prioridade atendimento</th>
                  <th style="text-align: center">Status</th>
                  <th style="text-align: center">Ações</th>
              </tr>
              <?php foreach($equipamentos as $equipamento): ?>
              <tr>
                <td style="text-align: center"><?= $equipamento['nome_fantasia'].' - '.$equipamento['nome_unidade']; ?></td>
                <td style="text-align: center"><?= $equipamento['etiqueta']; ?></td>
                <td style="text-align: center"><?= $equipamento['nome_rede']; ?></td>
                <td style="text-align: center"><?= $equipamento['descricao']; ?></td>
                <td style="text-align: center"><?= $this->status($equipamento['ativo']); ?></td>
                <td style="text-align: center;">
                  <img src="<?= $this->basePath('img/editar.png'); ?>" title="Editar" 
                  onclick="location.href='<?= $this->url('equipamentoAlterar', array('id' => $equipamento['id'])); ?>'" style="cursor: pointer;">
                  <span style="margin-right:4px;"></span>  
                  <img src="<?= $this->basePath('img/deletar.png'); ?>" title="Deletar" style="cursor: pointer;" onclick="alerta('<?= $this->url('equipamentoDeletar', array('id' => $equipamento['id'])) ?>', 'desativar');">
                </td>
              </tr>
              <?php endforeach; ?>
            </table>
          <?php else: ?>
            <div class="alert alert-info">Nenhum equipamento encontrado!</div>
        <?php endif; ?>
            </div>
          </div>
        </div>
      </div>

      <div class="container theme-showcase" style="margin-top:0px;" role="main">
        <div style="float:right;">
          <?php echo $this->paginationControl($equipamentos,
                                        'Sliding',
                                        'view/paginator', array('route' => 'equipamento')); 
          ?>
        </div>
      </div>
    <script type="text/javascript">
      $(document).ready(function() {
        formUnidade();
      });
    </script>