<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;margin-top: 50px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('listaTrabalhosAvaliador'); ?>">Trabalhos</a></li>
    <li><a href="<?= $this->url('visualizarTrabalhosAvaliador', array('idTrabalho' => $idTrabalho)); ?>">Visualizar trabalho</a></li>
    <li class="active">Avaliar</li>
  </ol>
</div>

<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-danger">
            <div class="panel-heading">
                <h3 class="panel-title">Avaliação escrita</h3>
            </div>
            <form name="frmAvaliar" action="#" method="POST">
            <div class="panel-body">
                <div class="form-group">
                <div class="row">
                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('normas')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;font-weight: 400">
                                <?= $this->formElement($formAvaliar->get('normas')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('normas'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('originalidade')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;">
                                <?= $this->formElement($formAvaliar->get('originalidade')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('originalidade'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('relevancia')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;">
                                <?= $this->formElement($formAvaliar->get('relevancia')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('relevancia'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row" style="margin-top:20px;">
                        <div class='col-sm-12'>
                            <div class="form-group">
                                <button type="submit" class="btn btn-danger" style="float: right;margin-right: 10px;">
                                    <img src="<?php echo $this->basePath('img/salvar.png') ?>" alt="Salvar">
                                    Salvar
                                </button>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            </form>
        </div>
    </div>
</div>
