<div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;margin-top: 50px;">
  <ol class="breadcrumb" style="margin-bottom: 0px;">
    <li><a href="<?= $this->url('listarTrabalhos'); ?>">Trabalhos</a></li>
    <li><a href="<?= $this->url('visualizarTrabalho', array('idInscricao' => $idInscricao)); ?>">Visualizar trabalho</a></li>
    <li class="active">Avaliar</li>
  </ol>
</div>

<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-info">
            <div class="panel-heading">
                <h3 class="panel-title">Avaliação oral</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                <div class="row">
                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('postura')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;">
                                <?= $this->formElement($formAvaliar->get('postura')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('postura'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('conhecimentos')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;">
                                <?= $this->formElement($formAvaliar->get('conhecimentos')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('conhecimentos'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class='col-sm-12'>
                        <div class="form-group">
                            <label for="disabledTextInput" style="font-size: 20px;"><?=$formAvaliar->get('clareza')->getLabel()?></label><br>
                            <div style="letter-spacing: 15px;">
                                <?= $this->formElement($formAvaliar->get('clareza')); ?>
                                <?= $this->formElementErrors($formAvaliar->get('clareza'), array('class' => 'alert alert-danger')); ?>
                            </div>
                        </div>
                    </div>

                    <div class="row" style="margin-top:20px;">
                        <div class='col-sm-12'>
                            <div class="form-group">
                                <a href="<?= $this->url('visualizarTrabalho', array('idInscricao' => $idInscricao)); ?>">
                                    <button type="button" class="btn btn-info" style="float: right;margin-right: 10px;">
                                        <img src="<?php echo $this->basePath('img/voltar.png') ?>" alt="Voltar">
                                        Voltar
                                    </button>
                                </a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>



<script type="text/javascript">

$(document).ready(function() {
  $("input[name='normas']").attr('disabled', 'disabled');
  $("input[name='postura']").attr('disabled', 'disabled');
  $("input[name='conhecimentos']").attr('disabled', 'disabled');
  $("input[name='originalidade']").attr('disabled', 'disabled');
  $("input[name='relevancia']").attr('disabled', 'disabled');
  $("input[name='clareza']").attr('disabled', 'disabled');

});
</script>