<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="stepwizard col-md-offset-3">
        <div class="stepwizard-row setup-panel">
          <div class="stepwizard-step">
            <a href="#step-1" type="button" class="btn btn-default btn-circle" disabled="disabled">1</a>
            <p>Modalidade</p>
          </div>
          <div class="stepwizard-step">
            <a href="#step-2" type="button" class="btn btn-primary btn-circle">2</a>
            <p>Cadastro</p>
          </div>
          <div class="stepwizard-step">
            <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
            <p>Pagamento</p>
          </div>
        </div>
      </div>
  </div>
</div>

<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-heading">
              <h3 class="panel-title">Cadastrar uma senha de acesso</h3>
            </div>
            <div class="panel-body">
                <div class="form-group">

                  <?php echo $this->partial('form/umacoluna', 
                		array(
                			'form'=> $formSenha
                		)); 
                	?>


    			</div>
    		</div>
    	</div>
    </div>
</div>


<script type="text/javascript">
  $(document).ready(function() {
        $('#login').attr('disabled', 'disabled');
      });

</script>