 <div class="container theme-showcase" role="main" style="margin-bottom:10px;padding:0px;">
    <ol class="breadcrumb" style="margin-bottom: 0px;">
      <li><a href="<?= $this->url('visualizaInscricoes'); ?>">Inscriçõoes realizadas</a></li>
      <li><a href="<?= $this->url('gerenciarInscricao', array('id' => $inscricao->id)); ?>">Inscrição</a></li>
      <li class="active">Pagar</li>
    </ol>
  </div>

    <div class="container theme-showcase" role="main">
      <div class="row">
          <div class="panel panel-default">
          <div class="panel-heading">
              <h3 class="panel-title">Inserir código promocional na inscrição do evento <?= $inscricao->nome_evento ?>, participante: <?= $inscricao->nome_completo ?></h3>
            </div>
            <div class="panel-body">
                <div class="form-group">
                  <?php echo $this->partial('form/generic', array('form'=> $formPromocao, 'route'=> '')) ?>

            </div>
          </div>
      </div>
    </div>
    </div>