<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="stepwizard col-md-offset-3">
        <div class="stepwizard-row setup-panel">
          <div class="stepwizard-step">
            <a href="#step-1" type="button" class="btn btn-default btn-circle" disabled="disabled">1</a>
            <p>Modalidade</p>
          </div>
          <div class="stepwizard-step">
            <a href="#step-2" type="button" class="btn btn-primary btn-circle">2</a>
            <p>Cadastro</p>
          </div>
          <div class="stepwizard-step">
            <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
            <p>Pagamento</p>
          </div>
        </div>
      </div>
  </div>
</div>

<?php if($tipoPessoa == 'F'): ?>
  <!-- GERAR RADIO PARA ESCOLHER TIPO DE PESSOA -->
  <div class="container theme-showcase" role="main">
    <div class="row">
    	<div class='col-sm-12'>
      		<!-- <label style="width:100%;">Tipo de pessoa:  (Caso precise de nota fiscal em nome de pessoa jurídica, escolha JURÍDICA)</label> -->
      	</div>
     </div>

    <div class="row">
    	<div class="col-sm-12">
	        <button type="button" class="btn btn-default active">
	          <img src="<?php echo $this->basePath('img/fisica.png') ?>" alt="Novo">
	           Física
	        </button>
        
			<button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('meusDadosInscricao', array('tipoPessoa' => 'J', 'siglaEvento' => $evento->sigla, 'valorInscricao' => $valor_inscricao)); ?>'" >
				<img src="<?php echo $this->basePath('img/juridica.png') ?>" alt="Novo">
				Jurídica
			</button>
        </div>
        
      </div>
    </div>
<?php else: ?>
	<div class="container theme-showcase" role="main">
	    <div class="row">
	    	<div class='col-sm-12'>
	      		<label style="width:100%">Tipo de pessoa: </label>
	      	</div>
	    </div>

	    <div class="row">
	    	<div class='col-sm-12'>
		        <button type="button" class="btn btn-default" onclick="location.href='<?= $this->url('meusDadosInscricao', array('tipoPessoa' => 'F', 'siglaEvento' => $evento->sigla, 'valorInscricao' => $valor_inscricao)); ?>'">
		          <img src="<?php echo $this->basePath('img/fisica.png') ?>" alt="Novo">
		           Física
		       	</button>
	        
		        <button type="button" class="btn btn-default active" >
		          <img src="<?php echo $this->basePath('img/juridica.png') ?>" alt="Novo">
		          Jurídica
		      	</button>
	      </div>
	    </div>
	</div>
<?php endif; ?>


<div class="container theme-showcase" role="main">
<div class="row">
  <hr>
</div>
</div>


<div class="container theme-showcase" role="main">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="form-group">
                  <div class="progress" id="progresso" style="display: none">
                    <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 60%;">
                      Carregando...
                    </div>
                  </div>

                  <?php echo $this->partial('form/meusdados', 
                		array(
                			'form'=> $formPessoa, 
                			'route'=> '', 
                			'valor_inscricao' => $valor_inscricao,
                      'reCaptchaValid'  => $reCaptchaValid,
                      'credenciais'     => $credenciais
                		)); 
                	?>


    			</div>
    		</div>
    	</div>
    </div>
</div>


<script type="text/javascript">
  $(document).ready(function() {
    formInscricao();
    $("#cpf").blur(function() {
      buscaCliente($("#cpf").val(), 'pessoaFisicaForm');
    });
  });
  
  $("#group-outro_conselho").hide();
  
  function outroConselho(idConselho){
    if(idConselho == 'Outro'){
    	$("#group-outro_conselho").show();
    	$("#outro_conselho").focus();
    }else{
    	$("#group-outro_conselho").hide();
    }
  }

  $("#cep").blur(function() {
    //buscar dados ajax
    cep = $("#cep").val();
    cep = cep.replace(".", "");
    cep = cep.replace("-", "");
    $.ajax({
      type: "GET",
      url: "http://viacep.com.br/ws/"+cep+"/json",
      success: function(json) {
        //$('#estado option[value='+json.uf+']').attr('selected','selected');
        $('#bairro').val(json.bairro);
        $('#nm_rua').val(json.logradouro);

        //ajax para procurar o estado e cidade
        buscarCep(json);
      }
    });
    //preencher e mudar foco para campo numero
  });

  function buscarCep(json){
    $.ajax({
      type: "GET",
      url: "/cep/buscar/"+json.uf+"/"+json.localidade,
      success: function(resp) {
        if(resp != "false"){
          var obj = $.parseJSON(resp);
          $("#estado").val(obj.estado);
          $("#cidade").val(obj.cidade);
          $("#numero").focus();
        }
      }
    });
  }

</script>