<div class="container theme-showcase" role="main">
	<div class="row">
		<div class="stepwizard col-md-offset-3">
		    <div class="stepwizard-row setup-panel">
		      <div class="stepwizard-step">
		        <a href="#step-1" type="button" class="btn btn-primary btn-circle">1</a>
		        <p>Modalidade</p>
		      </div>
		      <div class="stepwizard-step">
		        <a href="#step-2" type="button" class="btn btn-default btn-circle" disabled="disabled">2</a>
		        <p>Cadastro</p>
		      </div>
		      <div class="stepwizard-step">
		        <a href="#step-3" type="button" class="btn btn-default btn-circle" disabled="disabled">3</a>
		        <p>Pagamento</p>
		      </div>
		    </div>
		  </div>
	</div>
</div>
  

<div class="container theme-showcase" role="main">
  <div class="row">
    <div class="col-sm-6">
      <?= html_entity_decode($evento->observacoes); ?>
    </div>
    <div class="col-sm-6">
      <?php echo $this->partial('form/inscricao', array('valores' => $valores, 'evento' => $evento));
      ?>

    </div>

  </div>
</div> 
                  

    
